# Create indicators and find signals
This code is designed to calculate the features for model training.

We will also bring in if the target price was hit within 8 weeks for ML training and validation.

Each share has it's own trading pattern so we will train a different model for each share but use the same set of features, just the hyper paramenters will be tuned differenty.

V5 build - Normalise vs rolling max 5 year window

In [1]:
#Import libraries
import pandas as pd
import numpy as np
import re
import tables
import os
import datetime as dt
from rf_modules import *

In [2]:
#Import the ftse list
path = r"C:\Users\Robert\Documents\python_scripts\stock_trading_ml_modelling\historical_prices"
tick_ftse = pd.read_csv(path + r"\tick_ftse.csv")
tick_ftse = tick_ftse.iloc[:,1:]
for col in tick_ftse:
    tick_ftse.rename(columns={col:clean_col_name(col)},inplace=True)
tick_ftse.head()
tick_ftse['ticker'] = [re.sub('(?=[0-9A-Z])*\.(?=[0-9A-Z]+)','-',tick) for tick in tick_ftse['ticker']]
tick_ftse['ticker'] = [re.sub('[^0-9A-Z\-]','',tick) for tick in tick_ftse['ticker']]

In [3]:
#Import and combine prices files
df_prices_w = pd.read_hdf(path + r"\all_hist_prices_w.h5")
#Rename columns
for col in df_prices_w:
    df_prices_w.rename(columns={col:clean_col_name(col)},inplace=True)
#Drop unwanted columns
try:
    df_prices_w.drop(columns=["unnamed_0","index"],inplace=True)
except Exception as e:
    print(e)
#Reformat columns where neccessary
df_prices_w["date"] = df_prices_w["date"].astype("datetime64")
print(df_prices_w.shape)
print(df_prices_w.dtypes)
df_prices_w.head()

"['unnamed_0' 'index'] not found in axis"
(280168, 13)
ticker                 object
date           datetime64[ns]
high                  float64
low                   float64
volume                float64
open                  float64
close                 float64
change                float64
ema12                 float64
ema26                 float64
macd_line             float64
signal_line           float64
macd                  float64
dtype: object

,ticker,date,high,low,volume,open,close,change,ema12,ema26,macd_line,signal_line,macd
0,III,2007-12-31,1023.0,964.0,4511565.0,995.0,965.0,-30.0,NaN,NaN,NaN,NaN,NaN
1,III,2008-01-07,989.0,917.5,16056554.0,967.5,924.0,-43.5,NaN,NaN,NaN,NaN,NaN
2,III,2008-01-14,936.0,881.0,21691287.0,917.0,901.0,-16.0,NaN,NaN,NaN,NaN,NaN
3,III,2008-01-21,965.0,847.0,17850580.0,891.0,917.5,26.5,NaN,NaN,NaN,NaN,NaN
4,III,2008-01-28,971.0,903.0,12079245.0,911.0,961.0,50.0,NaN,NaN,NaN,NaN,NaN

In [4]:
#Remove tickers with fewer than 34 entries as this is where the MACD can be calculated
print('START ROW COUNT -> {}'.format(df_prices_w.shape[0]))
print('START TICK COUNT -> {}'.format(tick_ftse.shape[0]))
for tick in tick_ftse.ticker:
    print(tick,' ->',df_prices_w[df_prices_w.ticker == tick].shape[0])
    if df_prices_w[df_prices_w.ticker == tick].shape[0] < 34:
        #Remove from dataframe
        print('\tTOO FEW RECORDS FOR {}'.format(tick))
        df_prices_w = df_prices_w.loc[df_prices_w.ticker != tick]
        print('\tNEW ROW COUNT -> {}'.format(df_prices_w.shape[0]))
        #Remove from tick_ftse
        tick_ftse = tick_ftse.loc[tick_ftse.ticker != tick]
        print('\tNEW TICK COUNT -> {}'.format(tick_ftse.shape[0]))
print('\nEND ROW COUNT -> {}'.format(df_prices_w.shape[0]))
print('END TICK COUNT -> {}'.format(tick_ftse.shape[0]))

START ROW COUNT -> 280168
START TICK COUNT -> 351
III  -> 623
ABF  -> 1055
ADM  -> 363
AAL  -> 1018
ANTO  -> 1055
AHT  -> 1033
AZN  -> 1055
AUTO  -> 248
AVV  -> 1055
AV  -> 2788
BA  -> 1546
BARC  -> 1055
BDEV  -> 1055
BKG  -> 1055
BHP  -> 534
BP  -> 1575
BATS  -> 1055
BLND  -> 1055
BT-A  -> 1546
BNZL  -> 1052
BRBY  -> 910
CCL  -> 999
CNA  -> 1055
CCH  -> 346
CPG  -> 1041
CRH  -> 1041
CRDA  -> 1047
DCC  -> 1037
DGE  -> 1055
EVR  -> 424
EXPN  -> 688
FERG  -> 1056
FLTR  -> 28
	TOO FEW RECORDS FOR FLTR
	NEW ROW COUNT -> 280140
	NEW TICK COUNT -> 350
FRES  -> 606
GSK  -> 1055
GLEN  -> 448
HLMA  -> 1023
HL  -> 651
HIK  -> 718
HSX  -> 1022
HSBA  -> 1266
IMB  -> 1190
INF  -> 1076
IHG  -> 854
ITRK  -> 894
IAG  -> 866
ITV  -> 1022
JD  -> 92
JMAT  -> 1247
KGF  -> 1266
LAND  -> 1274
LGEN  -> 1266
LLOY  -> 1232
LSE  -> 942
MNG  -> 8
	TOO FEW RECORDS FOR MNG
	NEW ROW COUNT -> 280132
	NEW TICK COUNT -> 349
MGGT  -> 1485
MRO  -> 822
MNDI  -> 624
MRW  -> 1266
NG  -> 1253
NXT  -> 1533
NMC  -> 383
OCDO  -> 472
PSON  -> 1283
PSN  -> 1473
PHNX  -> 505
POLY  -> 406
PRU  -> 1512
RDSA  -> 267
RDSB  -> 1003
RB  -> 1293
REL  -> 1283
RTO  -> 1251
RMV  -> 700
RIO  -> 1536
RR  -> 1563
RBS  -> 1266
RSA  -> 1253
SGE  -> 1261
SBRY  -> 1266
SDR  -> 1256
SMT  -> 145
SGRO  -> 1544
SVT  -> 1251
SN  -> 1597
SMDS  -> 1434
SMIN  -> 1496
SKG  -> 647
SPX  -> 1464
SSE  -> 1283
STJ  -> 1472
STAN  -> 1537
SLA  -> 682
TW  -> 1563
TSCO  -> 1266
TUI  -> 261
ULVR  -> 1036
UU  -> 1302
VOD  -> 1055
WTB  -> 1055
WPP  -> 692
3IN  -> 595
FOUR  -> 1046
888  -> 742
ASL  -> 612
AGK  -> 1055
AAF  -> 24
	TOO FEW RECORDS FOR AAF
	NEW ROW COUNT -> 280108
	NEW TICK COUNT -> 348
AJB  -> 54
ATST  -> 624
APAX  -> 225
ASCL  -> 201
ASHM  -> 688
AGR  -> 837
AML  -> 63
AVST  -> 84
AGT  -> 20
	TOO FEW RECORDS FOR AGT
	NEW ROW COUNT -> 280088
	NEW TICK COUNT -> 347
BME  -> 288
BAB  -> 1035
BGFD  -> 615
BAKK  -> 109
BBY  -> 1055
BGEO  -> 628
BNKR  -> 618
BAG  -> 1055
BBGI  -> 407
BEZ  -> 171
BWY  -> 1443
BYG  -> 1004
BRSC  -> 283
BRWM  -> 591
BCPT  -> 18
	TOO FEW RECORDS FOR BCPT
	NEW ROW COUNT -> 280070
	NEW TICK COUNT -> 346
BGSC  -> 603
BOY  -> 1257
BVS  -> 1124
BRW  -> 1134
BVIC  -> 713
CNE  -> 1410
CLDN  -> 601
CAPC  -> 482
CPI  -> 1312
CARD  -> 292
CEY  -> 919
CINE  -> 641
CTY  -> 605
CKN  -> 1314
CBG  -> 1249
CLI  -> 1285
COA  -> 1382
COB  -> 1266
CCC  -> 1107
GLO  -> 110
CTEC  -> 164
CSP  -> 420
CWK  -> 1122
CRST  -> 338
DJAN  -> 1132
DPH  -> 964
DLN  -> 1203
DPLM  -> 1489
DLG  -> 356
DC  -> 533
DOM  -> 1028
DRX  -> 712
DNLM  -> 668
EZJ  -> 977
EDIN  -> 589
EIG  -> 670
ECM  -> 1266
ELM  -> 1544
ENOG  -> 92
ETO  -> 604
EQN  -> 216
ESNT  -> 739
JEO  -> 595
ERM  -> 1122
FCIT  -> 595
FDM  -> 287
FXPO  -> 628
FEV  -> 594
FSV  -> 594
FCSS  -> 474
FIN  -> 31
	TOO FEW RECORDS FOR FIN
	NEW ROW COUNT -> 280039
	NEW TICK COUNT -> 345
FGT  -> 589
FGP  -> 1259
FSJ  -> 1102
FSFL  -> 291
FUTR  -> 1050
GFS  -> 838
GFRD  -> 1472
GAW  -> 1294
GCP  -> 461
DIGS  -> 314
GSS  -> 603
GNS  -> 946
GOG  -> 1308
GPOR  -> 1036
GFTU  -> 906
GRI  -> 1055
UKW  -> 341
GNC  -> 1041
GRG  -> 1055
GVC  -> 746
HMSO  -> 1054
HVPE  -> 403
HSTG  -> 218
HAS  -> 1036
HSL  -> 611
HRI  -> 594
HGT  -> 594
HICL  -> 594
HILS  -> 1035
HFG  -> 637
HOC  -> 666
HSV  -> 1025
HWDN  -> 1036
HTG  -> 1005
IBST  -> 217
ICGT  -> 607
IGG  -> 745
IMI  -> 1036
INCH  -> 1036
ICP  -> 1036
IHP  -> 94
INPP  -> 518
INVP  -> 889
IPO  -> 825
IWG  -> 549
JLG  -> 253
JII  -> 603
JAM  -> 594
JMG  -> 594
JFJ  -> 605
JUP  -> 477
JE  -> 298
KNOS  -> 232
KAZ  -> 722
LRE  -> 712
LWDB  -> 392
LMP  -> 520
EMG  -> 1036
MKS  -> 1036
MSLH  -> 1036
MARS  -> 788
MCS  -> 113
MDC  -> 200
MRC  -> 577
MCRO  -> 743
MAB  -> 852
MONY  -> 622
MNKS  -> 595
MGAM  -> 1473
MYI  -> 594
NEX  -> 1375
NBLS  -> 421
NETW  -> 36
NRR  -> 474
NESF  -> 285
OSB  -> 289
OXIG  -> 1469
PAGE  -> 926
PIN  -> 594
PAG  -> 1490
PAY  -> 776
PNN  -> 1529
PLI  -> 594
PSH  -> 136
PNL  -> 595
PFC  -> 722
PETS  -> 301
PTEC  -> 697
PLUS  -> 315
PCT  -> 596
PSSL  -> 12
	TOO FEW RECORDS FOR PSSL
	NEW ROW COUNT -> 280027
	NEW TICK COUNT -> 344
PLP  -> 297
PPH  -> 582
PMO  -> 1467
PHP  -> 1093
PFG  -> 1036
PRTC  -> 235
PZC  -> 1021
QQ  -> 723
QLT  -> 77
RNK  -> 1036
RAT  -> 1029
RDW  -> 1033
TRIG  -> 305
RSW  -> 1030
RTN  -> 1036
RHIM  -> 112
RCP  -> 83
RSE  -> 293
ROR  -> 1036
RMG  -> 304
SBRE  -> 106
SAFE  -> 472
SNN  -> 246
SVS  -> 1422
SDP  -> 596
SOI  -> 594
SCIN  -> 596
SNR  -> 1438
SEQI  -> 240
SRP  -> 1295
SHB  -> 1162
SHI  -> 1328
SIG  -> 2
	TOO FEW RECORDS FOR SIG
	NEW ROW COUNT -> 280025
	NEW TICK COUNT -> 343
SRE  -> 633
SSON  -> 51
SCT  -> 214
SOPH  -> 234
SXS  -> 1488
SPT  -> 1265
SPD  -> 649
SSPG  -> 284
SMP  -> 1433
SGC  -> 1161
SYNC  -> 345
SYNT  -> 1463
TALK  -> 489
TATE  -> 1270
TBCG  -> 175
TEP  -> 993
TMPL  -> 596
TEM  -> 595
TIFS  -> 112
TCAP  -> 970
TRY  -> 594
TRN  -> 25
	TOO FEW RECORDS FOR TRN
	NEW ROW COUNT -> 280000
	NEW TICK COUNT -> 342
TPK  -> 1036
BBOX  -> 286
TLW  -> 1028
UDG  -> 1017
UKCM  -> 596
ULE  -> 1032
UTG  -> 352
VSVS  -> 1266
VCT  -> 1195
VEIL  -> 170
VOF  -> 604
VMUK  -> 5
	TOO FEW RECORDS FOR VMUK
	NEW ROW COUNT -> 279995
	NEW TICK COUNT -> 341
VVO  -> 85
WOSG  -> 28
	TOO FEW RECORDS FOR WOSG
	NEW ROW COUNT -> 279967
	NEW TICK COUNT -> 340
WEIR  -> 1478
JDW  -> 1352
SMWH  -> 678
WMH  -> 894
WTAN  -> 603
WIZZ  -> 251
WG  -> 916
WKP  -> 956
WWH  -> 605

END ROW COUNT -> 279967
END TICK COUNT -> 340

In [5]:
#Function for calculating ema
def calc_ema(_s_in,_periods):
    """Function used to create EMA for a series
    
    args:
    -----
    _s_in - pandas series - series of float values
    _periods - int - value describing how far to look at for EMA calc
    
    returns:
    ------
    pandas series    
    """
    #Calc mod val
    _mod = 2/(_periods+1)
    #Calc sma
    _sma_s = [0] * _s_in.shape[0]
    for _i in range(0,_periods):
        _sma_s += _s_in.shift(_i) / _periods
    #Calc ema
    _ema_s = _sma_s.copy()
    _ema_s[(_ema_s > 0) & (np.isnan(_ema_s) == False)] = _mod*(_s_in - _ema_s.shift(1)) + _ema_s.shift(1)
    return _ema_s.copy()

In [6]:
#Function for calculating the MACD
def calc_macd(_ema_lng_s,_ema_sht_s,_sig_period:int):
    """Function used to create MACD for a series
    
    args:
    -----
    _ema_lng_s - pandas series - series of float values for the long term EMA 
    _ema_sht_s - pandas series - series of float values for the short term EMA
    _sig_period - int - value describing how far to look at for MACD calc
    
    returns:
    ------
    tuple of pandas series,pandas series,pandas series - MACD line, signal line, macd histogram  
    """
    #Make a df
    _tmp_df = pd.DataFrame([])
    _tmp_df['ema_lng'] = _ema_lng_s
    _tmp_df['ema_sht'] = _ema_sht_s
    #Calc the signal line
    _tmp_df['macd_line'] = _tmp_df['ema_sht'] - _tmp_df['ema_lng']
    _tmp_df['signal_line'] = calc_ema(_tmp_df['macd_line'],_sig_period)
    _tmp_df['macd_hist'] = _tmp_df['macd_line'] - _tmp_df['signal_line']
    return (_tmp_df['macd_line'].copy(),_tmp_df['signal_line'].copy(),_tmp_df['macd_hist'].copy())

In [7]:
#Calc the ema and macds for the data
def calc_ema_macd(_df_in):
    """Function used to call EMA and MACD functions
    
    args:
    -----
    _df_in - pandas dataframe - must have columns 'close' and 'date' 
    
    returns:
    ------
    pandas dataframe - with new columns for ema12,ema26,macd_line,signal_line,macd
    """
    _tick_df = _df_in.copy()
    try:
        #Add in the ema and macd
        _tick_df = _tick_df.sort_values(by='date')
#         _tick_df = _tick_df.reset_index(drop=True)
        _tick_df['ema12'] = calc_ema(_tick_df['close'],12)
        _tick_df['ema26'] = calc_ema(_tick_df['close'],26)
        _tick_df['macd_line'],_tick_df['signal_line'],_tick_df['macd'] = calc_macd(_tick_df['ema26'],_tick_df['ema12'],9)
        return _tick_df
    except Exception as e:
        print('ERROR:{}'.format(e))
        return _tick_df

In [8]:
#Create a function which normalises a feature based only on the values which have come before it - avoids time series bias
def norm_time_s(_ind,_s_in,_window):
    """Function used to call EMA and MACD functions
    
    args:
    -----
    _ind - int - the index of this value in the series
    _s_in - pandas series - a series of values to be normalised
    _window - int - the number of values to look over
    
    returns:
    ------
    float - normalised value in the window period
    """
    _this_ind = _ind - _s_in.index.min()
    if _this_ind < _window:
        _st_ind = 0
    else:
        _st_ind = _this_ind - _window
    _min = np.nanmin(_s_in[_st_ind:_this_ind+1].values)
    _max = np.nanmax(_s_in[_st_ind:_this_ind+1].values)
    _norm_val = (_s_in[_ind] - _min) / (_max - _min)
    return _norm_val

In [9]:
#Run the functions
def norm_prices(_df_in):
    """Function used to normalise all prices in the dataframe
    
    args:
    -----
    _df_in - pandas dataframe - must contain values 'open','close','high','low','volume'
    
    returns:
    ------
    pandas dataframe - with normalised values for 'open','close','high','low','volume'
    """
    _df_out = _df_in.copy()
    #Normalise the columns which need it
    _norm_cols = [
        #Standard features
        "open"
        ,"close"
        ,"high"
        ,"low"
        ,"volume"
    ]
    #Reset the index
    _df_out.sort_values(['date'],ascending=True,inplace=True)
    #Calc the 5yr window
    _5yr = 5*52
    #Normalise
    for _col in _norm_cols:
        _df_out["{}_orig".format(_col)] = _df_out[_col].copy() #Take a copy so as the values are changed this does not affect following calculations
        _df_out[_col] = [norm_time_s(_x,_df_out["{}_orig".format(_col)],_5yr) for _x in _df_out.index]
    return _df_out

In [10]:
#Set records into the correct order
df_prices_w = df_prices_w.sort_values(['ticker','date'],ascending=[True,True])
df_prices_w.reset_index(inplace=True,drop=True)

In [11]:
# Normalize the prices by ticker and time then create emas and macds for each ticker
print('NORALISING AND CALCULATING EMA & MACD VALUES')
error_li = []
run_time = process_time()
run_time.lap()
new_df = pd.DataFrame([])
for tick in tick_ftse.ticker:
    print('\nRUN FOR {} - {}'.format(tick,len(run_time.lap_li)))
    try:
        this_tick_df = df_prices_w[df_prices_w.ticker == tick]
        this_tick_df = norm_prices(this_tick_df.copy())
        #Calculate the ema and macd
        this_tick_df = calc_ema_macd(this_tick_df)
        #Append back on to the dataframe
        new_df = new_df.append(this_tick_df)
        print('\tSUCCESS')
        run_time.lap()
        run_time.show_latest_lap_time()
    except Exception as e:
        print('\tERROR -> {}'.format(e))
        error_li.append(e)
df_prices_w = new_df
run_time.end()
print('\n\nCOMPLETED - ERRORS ENCOUNTERED -> {}'.format(len(error_li)))
if len(error_li) > 0:
    print(error_li)

NORALISING AND CALCULATING EMA & MACD VALUES

RUN FOR III - 1

C:\Users\Robert\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in double_scalars

	SUCCESS
LAP 2 TIME -> 0:0:1

RUN FOR ABF - 2
	SUCCESS
LAP 3 TIME -> 0:0:2

RUN FOR ADM - 3
	SUCCESS
LAP 4 TIME -> 0:0:0

RUN FOR AAL - 4
	SUCCESS
LAP 5 TIME -> 0:0:2

RUN FOR ANTO - 5
	SUCCESS
LAP 6 TIME -> 0:0:2

RUN FOR AHT - 6
	SUCCESS
LAP 7 TIME -> 0:0:2

RUN FOR AZN - 7
	SUCCESS
LAP 8 TIME -> 0:0:2

RUN FOR AUTO - 8
	SUCCESS
LAP 9 TIME -> 0:0:0

RUN FOR AVV - 9
	SUCCESS
LAP 10 TIME -> 0:0:2

RUN FOR AV - 10
	SUCCESS
LAP 11 TIME -> 0:0:6

RUN FOR BA - 11
	SUCCESS
LAP 12 TIME -> 0:0:3

RUN FOR BARC - 12
	SUCCESS
LAP 13 TIME -> 0:0:2

RUN FOR BDEV - 13
	SUCCESS
LAP 14 TIME -> 0:0:2

RUN FOR BKG - 14
	SUCCESS
LAP 15 TIME -> 0:0:2

RUN FOR BHP - 15
	SUCCESS
LAP 16 TIME -> 0:0:1

RUN FOR BP - 16
	SUCCESS
LAP 17 TIME -> 0:0:3

RUN FOR BATS - 17
	SUCCESS
LAP 18 TIME -> 0:0:2

RUN FOR BLND - 18
	SUCCESS
LAP 19 TIME -> 0:0:2

RUN FOR BT-A - 19
	SUCCESS
LAP 20 TIME -> 0:0:3

RUN FOR BNZL - 20
	SUCCESS
LAP 21 TIME -> 0:0:2

RUN FOR BRBY - 21
	SUCCESS
LAP 22 TIME -> 0:0:2

RUN FOR CCL - 22
	SUCCESS
LAP 23 TIME -> 0:0:2

RUN FOR CNA - 23
	SUCCESS
LAP 24 TIME -> 0:0:2

RUN FOR CCH - 24
	SUCCESS
LAP 25 TIME -> 0:0:0

RUN FOR CPG - 25
	SUCCESS
LAP 26 TIME -> 0:0:2

RUN FOR CRH - 26
	SUCCESS
LAP 27 TIME -> 0:0:2

RUN FOR CRDA - 27
	SUCCESS
LAP 28 TIME -> 0:0:2

RUN FOR DCC - 28
	SUCCESS
LAP 29 TIME -> 0:0:2

RUN FOR DGE - 29
	SUCCESS
LAP 30 TIME -> 0:0:2

RUN FOR EVR - 30
	SUCCESS
LAP 31 TIME -> 0:0:1

RUN FOR EXPN - 31
	SUCCESS
LAP 32 TIME -> 0:0:1

RUN FOR FERG - 32
	SUCCESS
LAP 33 TIME -> 0:0:2

RUN FOR FRES - 33
	SUCCESS
LAP 34 TIME -> 0:0:1

RUN FOR GSK - 34
	SUCCESS
LAP 35 TIME -> 0:0:2

RUN FOR GLEN - 35
	SUCCESS
LAP 36 TIME -> 0:0:1

RUN FOR HLMA - 36
	SUCCESS
LAP 37 TIME -> 0:0:2

RUN FOR HL - 37
	SUCCESS
LAP 38 TIME -> 0:0:1

RUN FOR HIK - 38
	SUCCESS
LAP 39 TIME -> 0:0:1

RUN FOR HSX - 39
	SUCCESS
LAP 40 TIME -> 0:0:2

RUN FOR HSBA - 40
	SUCCESS
LAP 41 TIME -> 0:0:2

RUN FOR IMB - 41
	SUCCESS
LAP 42 TIME -> 0:0:2

RUN FOR INF - 42
	SUCCESS
LAP 43 TIME -> 0:0:2

RUN FOR IHG - 43
	SUCCESS
LAP 44 TIME -> 0:0:1

RUN FOR ITRK - 44
	SUCCESS
LAP 45 TIME -> 0:0:2

RUN FOR IAG - 45
	SUCCESS
LAP 46 TIME -> 0:0:2

RUN FOR ITV - 46
	SUCCESS
LAP 47 TIME -> 0:0:2

RUN FOR JD - 47
	SUCCESS
LAP 48 TIME -> 0:0:0

RUN FOR JMAT - 48
	SUCCESS
LAP 49 TIME -> 0:0:2

RUN FOR KGF - 49
	SUCCESS
LAP 50 TIME -> 0:0:2

RUN FOR LAND - 50
	SUCCESS
LAP 51 TIME -> 0:0:3

RUN FOR LGEN - 51
	SUCCESS
LAP 52 TIME -> 0:0:3

RUN FOR LLOY - 52
	SUCCESS
LAP 53 TIME -> 0:0:3

RUN FOR LSE - 53
	SUCCESS
LAP 54 TIME -> 0:0:2

RUN FOR MGGT - 54
	SUCCESS
LAP 55 TIME -> 0:0:3

RUN FOR MRO - 55
	SUCCESS
LAP 56 TIME -> 0:0:1

RUN FOR MNDI - 56
	SUCCESS
LAP 57 TIME -> 0:0:1

RUN FOR MRW - 57
	SUCCESS
LAP 58 TIME -> 0:0:2

RUN FOR NG - 58
	SUCCESS
LAP 59 TIME -> 0:0:2

RUN FOR NXT - 59
	SUCCESS
LAP 60 TIME -> 0:0:3

RUN FOR NMC - 60
	SUCCESS
LAP 61 TIME -> 0:0:0

RUN FOR OCDO - 61
	SUCCESS
LAP 62 TIME -> 0:0:1

RUN FOR PSON - 62
	SUCCESS
LAP 63 TIME -> 0:0:2

RUN FOR PSN - 63
	SUCCESS
LAP 64 TIME -> 0:0:3

RUN FOR PHNX - 64
	SUCCESS
LAP 65 TIME -> 0:0:1

RUN FOR POLY - 65
	SUCCESS
LAP 66 TIME -> 0:0:1

RUN FOR PRU - 66
	SUCCESS
LAP 67 TIME -> 0:0:3

RUN FOR RDSA - 67
	SUCCESS
LAP 68 TIME -> 0:0:0

RUN FOR RDSB - 68
	SUCCESS
LAP 69 TIME -> 0:0:2

RUN FOR RB - 69
	SUCCESS
LAP 70 TIME -> 0:0:2

RUN FOR REL - 70
	SUCCESS
LAP 71 TIME -> 0:0:2

RUN FOR RTO - 71
	SUCCESS
LAP 72 TIME -> 0:0:2

RUN FOR RMV - 72
	SUCCESS
LAP 73 TIME -> 0:0:1

RUN FOR RIO - 73
	SUCCESS
LAP 74 TIME -> 0:0:3

RUN FOR RR - 74
	SUCCESS
LAP 75 TIME -> 0:0:3

RUN FOR RBS - 75
	SUCCESS
LAP 76 TIME -> 0:0:2

RUN FOR RSA - 76
	SUCCESS
LAP 77 TIME -> 0:0:2

RUN FOR SGE - 77
	SUCCESS
LAP 78 TIME -> 0:0:2

RUN FOR SBRY - 78
	SUCCESS
LAP 79 TIME -> 0:0:2

RUN FOR SDR - 79
	SUCCESS
LAP 80 TIME -> 0:0:2

RUN FOR SMT - 80
	SUCCESS
LAP 81 TIME -> 0:0:0

RUN FOR SGRO - 81
	SUCCESS
LAP 82 TIME -> 0:0:3

RUN FOR SVT - 82
	SUCCESS
LAP 83 TIME -> 0:0:2

RUN FOR SN - 83
	SUCCESS
LAP 84 TIME -> 0:0:3

RUN FOR SMDS - 84
	SUCCESS
LAP 85 TIME -> 0:0:3

RUN FOR SMIN - 85
	SUCCESS
LAP 86 TIME -> 0:0:3

RUN FOR SKG - 86
	SUCCESS
LAP 87 TIME -> 0:0:1

RUN FOR SPX - 87
	SUCCESS
LAP 88 TIME -> 0:0:3

RUN FOR SSE - 88
	SUCCESS
LAP 89 TIME -> 0:0:2

RUN FOR STJ - 89
	SUCCESS
LAP 90 TIME -> 0:0:3

RUN FOR STAN - 90
	SUCCESS
LAP 91 TIME -> 0:0:3

RUN FOR SLA - 91
	SUCCESS
LAP 92 TIME -> 0:0:1

RUN FOR TW - 92
	SUCCESS
LAP 93 TIME -> 0:0:3

RUN FOR TSCO - 93
	SUCCESS
LAP 94 TIME -> 0:0:2

RUN FOR TUI - 94
	SUCCESS
LAP 95 TIME -> 0:0:0

RUN FOR ULVR - 95
	SUCCESS
LAP 96 TIME -> 0:0:2

RUN FOR UU - 96
	SUCCESS
LAP 97 TIME -> 0:0:2

RUN FOR VOD - 97
	SUCCESS
LAP 98 TIME -> 0:0:2

RUN FOR WTB - 98
	SUCCESS
LAP 99 TIME -> 0:0:2

RUN FOR WPP - 99
	SUCCESS
LAP 100 TIME -> 0:0:1

RUN FOR 3IN - 100
	SUCCESS
LAP 101 TIME -> 0:0:1

RUN FOR FOUR - 101
	SUCCESS
LAP 102 TIME -> 0:0:2

RUN FOR 888 - 102
	SUCCESS
LAP 103 TIME -> 0:0:1

RUN FOR ASL - 103
	SUCCESS
LAP 104 TIME -> 0:0:1

RUN FOR AGK - 104
	SUCCESS
LAP 105 TIME -> 0:0:2

RUN FOR AJB - 105
	SUCCESS
LAP 106 TIME -> 0:0:0

RUN FOR ATST - 106
	SUCCESS
LAP 107 TIME -> 0:0:1

RUN FOR APAX - 107
	SUCCESS
LAP 108 TIME -> 0:0:0

RUN FOR ASCL - 108
	SUCCESS
LAP 109 TIME -> 0:0:0

RUN FOR ASHM - 109
	SUCCESS
LAP 110 TIME -> 0:0:1

RUN FOR AGR - 110
	SUCCESS
LAP 111 TIME -> 0:0:1

RUN FOR AML - 111
	SUCCESS
LAP 112 TIME -> 0:0:0

RUN FOR AVST - 112
	SUCCESS
LAP 113 TIME -> 0:0:0

RUN FOR BME - 113
	SUCCESS
LAP 114 TIME -> 0:0:0

RUN FOR BAB - 114
	SUCCESS
LAP 115 TIME -> 0:0:2

RUN FOR BGFD - 115
	SUCCESS
LAP 116 TIME -> 0:0:1

RUN FOR BAKK - 116
	SUCCESS
LAP 117 TIME -> 0:0:0

RUN FOR BBY - 117
	SUCCESS
LAP 118 TIME -> 0:0:2

RUN FOR BGEO - 118
	SUCCESS
LAP 119 TIME -> 0:0:1

RUN FOR BNKR - 119
	SUCCESS
LAP 120 TIME -> 0:0:1

RUN FOR BAG - 120
	SUCCESS
LAP 121 TIME -> 0:0:2

RUN FOR BBGI - 121
	SUCCESS
LAP 122 TIME -> 0:0:0

RUN FOR BEZ - 122
	SUCCESS
LAP 123 TIME -> 0:0:0

RUN FOR BWY - 123
	SUCCESS
LAP 124 TIME -> 0:0:3

RUN FOR BYG - 124
	SUCCESS
LAP 125 TIME -> 0:0:2

RUN FOR BRSC - 125
	SUCCESS
LAP 126 TIME -> 0:0:0

RUN FOR BRWM - 126
	SUCCESS
LAP 127 TIME -> 0:0:1

RUN FOR BGSC - 127
	SUCCESS
LAP 128 TIME -> 0:0:1

RUN FOR BOY - 128
	SUCCESS
LAP 129 TIME -> 0:0:2

RUN FOR BVS - 129
	SUCCESS
LAP 130 TIME -> 0:0:2

RUN FOR BRW - 130
	SUCCESS
LAP 131 TIME -> 0:0:2

RUN FOR BVIC - 131
	SUCCESS
LAP 132 TIME -> 0:0:1

RUN FOR CNE - 132
	SUCCESS
LAP 133 TIME -> 0:0:3

RUN FOR CLDN - 133
	SUCCESS
LAP 134 TIME -> 0:0:1

RUN FOR CAPC - 134
	SUCCESS
LAP 135 TIME -> 0:0:1

RUN FOR CPI - 135
	SUCCESS
LAP 136 TIME -> 0:0:2

RUN FOR CARD - 136
	SUCCESS
LAP 137 TIME -> 0:0:0

RUN FOR CEY - 137
	SUCCESS
LAP 138 TIME -> 0:0:2

RUN FOR CINE - 138
	SUCCESS
LAP 139 TIME -> 0:0:1

RUN FOR CTY - 139
	SUCCESS
LAP 140 TIME -> 0:0:1

RUN FOR CKN - 140
	SUCCESS
LAP 141 TIME -> 0:0:3

RUN FOR CBG - 141
	SUCCESS
LAP 142 TIME -> 0:0:2

RUN FOR CLI - 142
	SUCCESS
LAP 143 TIME -> 0:0:2

RUN FOR COA - 143
	SUCCESS
LAP 144 TIME -> 0:0:3

RUN FOR COB - 144
	SUCCESS
LAP 145 TIME -> 0:0:2

RUN FOR CCC - 145
	SUCCESS
LAP 146 TIME -> 0:0:2

RUN FOR GLO - 146
	SUCCESS
LAP 147 TIME -> 0:0:0

RUN FOR CTEC - 147
	SUCCESS
LAP 148 TIME -> 0:0:0

RUN FOR CSP - 148
	SUCCESS
LAP 149 TIME -> 0:0:1

RUN FOR CWK - 149
	SUCCESS
LAP 150 TIME -> 0:0:2

RUN FOR CRST - 150
	SUCCESS
LAP 151 TIME -> 0:0:0

RUN FOR DJAN - 151
	SUCCESS
LAP 152 TIME -> 0:0:2

RUN FOR DPH - 152
	SUCCESS
LAP 153 TIME -> 0:0:2

RUN FOR DLN - 153
	SUCCESS
LAP 154 TIME -> 0:0:2

RUN FOR DPLM - 154
	SUCCESS
LAP 155 TIME -> 0:0:3

RUN FOR DLG - 155
	SUCCESS
LAP 156 TIME -> 0:0:0

RUN FOR DC - 156
	SUCCESS
LAP 157 TIME -> 0:0:1

RUN FOR DOM - 157
	SUCCESS
LAP 158 TIME -> 0:0:2

RUN FOR DRX - 158
	SUCCESS
LAP 159 TIME -> 0:0:1

RUN FOR DNLM - 159
	SUCCESS
LAP 160 TIME -> 0:0:1

RUN FOR EZJ - 160
	SUCCESS
LAP 161 TIME -> 0:0:2

RUN FOR EDIN - 161
	SUCCESS
LAP 162 TIME -> 0:0:1

RUN FOR EIG - 162
	SUCCESS
LAP 163 TIME -> 0:0:1

RUN FOR ECM - 163
	SUCCESS
LAP 164 TIME -> 0:0:2

RUN FOR ELM - 164
	SUCCESS
LAP 165 TIME -> 0:0:3

RUN FOR ENOG - 165
	SUCCESS
LAP 166 TIME -> 0:0:0

RUN FOR ETO - 166
	SUCCESS
LAP 167 TIME -> 0:0:1

RUN FOR EQN - 167
	SUCCESS
LAP 168 TIME -> 0:0:0

RUN FOR ESNT - 168
	SUCCESS
LAP 169 TIME -> 0:0:1

RUN FOR JEO - 169

	SUCCESS
LAP 170 TIME -> 0:0:1

RUN FOR ERM - 170
	SUCCESS
LAP 171 TIME -> 0:0:2

RUN FOR FCIT - 171
	SUCCESS
LAP 172 TIME -> 0:0:1

RUN FOR FDM - 172
	SUCCESS
LAP 173 TIME -> 0:0:0

RUN FOR FXPO - 173
	SUCCESS
LAP 174 TIME -> 0:0:1

RUN FOR FEV - 174
	SUCCESS
LAP 175 TIME -> 0:0:1

RUN FOR FSV - 175
	SUCCESS
LAP 176 TIME -> 0:0:1

RUN FOR FCSS - 176
	SUCCESS
LAP 177 TIME -> 0:0:1

RUN FOR FGT - 177
	SUCCESS
LAP 178 TIME -> 0:0:1

RUN FOR FGP - 178
	SUCCESS
LAP 179 TIME -> 0:0:2

RUN FOR FSJ - 179
	SUCCESS
LAP 180 TIME -> 0:0:2

RUN FOR FSFL - 180
	SUCCESS
LAP 181 TIME -> 0:0:0

RUN FOR FUTR - 181
	SUCCESS
LAP 182 TIME -> 0:0:2

RUN FOR GFS - 182
	SUCCESS
LAP 183 TIME -> 0:0:1

RUN FOR GFRD - 183
	SUCCESS
LAP 184 TIME -> 0:0:3

RUN FOR GAW - 184
	SUCCESS
LAP 185 TIME -> 0:0:3

RUN FOR GCP - 185
	SUCCESS
LAP 186 TIME -> 0:0:1

RUN FOR DIGS - 186
	SUCCESS
LAP 187 TIME -> 0:0:0

RUN FOR GSS - 187
	SUCCESS
LAP 188 TIME -> 0:0:1

RUN FOR GNS - 188
	SUCCESS
LAP 189 TIME -> 0:0:2

RUN FOR GOG - 189
	SUCCESS
LAP 190 TIME -> 0:0:3

RUN FOR GPOR - 190
	SUCCESS
LAP 191 TIME -> 0:0:2

RUN FOR GFTU - 191
	SUCCESS
LAP 192 TIME -> 0:0:2

RUN FOR GRI - 192
	SUCCESS
LAP 193 TIME -> 0:0:2

RUN FOR UKW - 193
	SUCCESS
LAP 194 TIME -> 0:0:0

RUN FOR GNC - 194
	SUCCESS
LAP 195 TIME -> 0:0:2

RUN FOR GRG - 195
	SUCCESS
LAP 196 TIME -> 0:0:2

RUN FOR GVC - 196
	SUCCESS
LAP 197 TIME -> 0:0:1

RUN FOR HMSO - 197
	SUCCESS
LAP 198 TIME -> 0:0:2

RUN FOR HVPE - 198
	SUCCESS
LAP 199 TIME -> 0:0:1

RUN FOR HSTG - 199
	SUCCESS
LAP 200 TIME -> 0:0:0

RUN FOR HAS - 200
	SUCCESS
LAP 201 TIME -> 0:0:2

RUN FOR HSL - 201
	SUCCESS
LAP 202 TIME -> 0:0:1

RUN FOR HRI - 202
	SUCCESS
LAP 203 TIME -> 0:0:1

RUN FOR HGT - 203
	SUCCESS
LAP 204 TIME -> 0:0:1

RUN FOR HICL - 204
	SUCCESS
LAP 205 TIME -> 0:0:1

RUN FOR HILS - 205
	SUCCESS
LAP 206 TIME -> 0:0:3

RUN FOR HFG - 206
	SUCCESS
LAP 207 TIME -> 0:0:1

RUN FOR HOC - 207
	SUCCESS
LAP 208 TIME -> 0:0:2

RUN FOR HSV - 208
	SUCCESS
LAP 209 TIME -> 0:0:2

RUN FOR HWDN - 209
	SUCCESS
LAP 210 TIME -> 0:0:2

RUN FOR HTG - 210
	SUCCESS
LAP 211 TIME -> 0:0:2

RUN FOR IBST - 211
	SUCCESS
LAP 212 TIME -> 0:0:0

RUN FOR ICGT - 212
	SUCCESS
LAP 213 TIME -> 0:0:1

RUN FOR IGG - 213
	SUCCESS
LAP 214 TIME -> 0:0:1

RUN FOR IMI - 214
	SUCCESS
LAP 215 TIME -> 0:0:2

RUN FOR INCH - 215
	SUCCESS
LAP 216 TIME -> 0:0:2

RUN FOR ICP - 216
	SUCCESS
LAP 217 TIME -> 0:0:2

RUN FOR IHP - 217
	SUCCESS
LAP 218 TIME -> 0:0:0

RUN FOR INPP - 218
	SUCCESS
LAP 219 TIME -> 0:0:1

RUN FOR INVP - 219
	SUCCESS
LAP 220 TIME -> 0:0:2

RUN FOR IPO - 220
	SUCCESS
LAP 221 TIME -> 0:0:1

RUN FOR IWG - 221
	SUCCESS
LAP 222 TIME -> 0:0:1

RUN FOR JLG - 222
	SUCCESS
LAP 223 TIME -> 0:0:0

RUN FOR JII - 223
	SUCCESS
LAP 224 TIME -> 0:0:1

RUN FOR JAM - 224
	SUCCESS
LAP 225 TIME -> 0:0:1

RUN FOR JMG - 225
	SUCCESS
LAP 226 TIME -> 0:0:1

RUN FOR JFJ - 226
	SUCCESS
LAP 227 TIME -> 0:0:1

RUN FOR JUP - 227
	SUCCESS
LAP 228 TIME -> 0:0:1

RUN FOR JE - 228
	SUCCESS
LAP 229 TIME -> 0:0:0

RUN FOR KNOS - 229
	SUCCESS
LAP 230 TIME -> 0:0:0

RUN FOR KAZ - 230
	SUCCESS
LAP 231 TIME -> 0:0:1

RUN FOR LRE - 231
	SUCCESS
LAP 232 TIME -> 0:0:1

RUN FOR LWDB - 232
	SUCCESS
LAP 233 TIME -> 0:0:1

RUN FOR LMP - 233
	SUCCESS
LAP 234 TIME -> 0:0:1

RUN FOR EMG - 234
	SUCCESS
LAP 235 TIME -> 0:0:2

RUN FOR MKS - 235
	SUCCESS
LAP 236 TIME -> 0:0:2

RUN FOR MSLH - 236
	SUCCESS
LAP 237 TIME -> 0:0:2

RUN FOR MARS - 237
	SUCCESS
LAP 238 TIME -> 0:0:2

RUN FOR MCS - 238
	SUCCESS
LAP 239 TIME -> 0:0:0

RUN FOR MDC - 239
	SUCCESS
LAP 240 TIME -> 0:0:0

RUN FOR MRC - 240
	SUCCESS
LAP 241 TIME -> 0:0:1

RUN FOR MCRO - 241
	SUCCESS
LAP 242 TIME -> 0:0:1

RUN FOR MAB - 242
	SUCCESS
LAP 243 TIME -> 0:0:1

RUN FOR MONY - 243
	SUCCESS
LAP 244 TIME -> 0:0:1

RUN FOR MNKS - 244
	SUCCESS
LAP 245 TIME -> 0:0:1

RUN FOR MGAM - 245
	SUCCESS
LAP 246 TIME -> 0:0:3

RUN FOR MYI - 246
	SUCCESS
LAP 247 TIME -> 0:0:1

RUN FOR NEX - 247
	SUCCESS
LAP 248 TIME -> 0:0:3

RUN FOR NBLS - 248
	SUCCESS
LAP 249 TIME -> 0:0:1

RUN FOR NETW - 249
	SUCCESS
LAP 250 TIME -> 0:0:0

RUN FOR NRR - 250
	SUCCESS
LAP 251 TIME -> 0:0:1

RUN FOR NESF - 251
	SUCCESS
LAP 252 TIME -> 0:0:0

RUN FOR OSB - 252
	SUCCESS
LAP 253 TIME -> 0:0:0

RUN FOR OXIG - 253
	SUCCESS
LAP 254 TIME -> 0:0:3

RUN FOR PAGE - 254
	SUCCESS
LAP 255 TIME -> 0:0:2

RUN FOR PIN - 255
	SUCCESS
LAP 256 TIME -> 0:0:1

RUN FOR PAG - 256
	SUCCESS
LAP 257 TIME -> 0:0:3

RUN FOR PAY - 257
	SUCCESS
LAP 258 TIME -> 0:0:1

RUN FOR PNN - 258
	SUCCESS
LAP 259 TIME -> 0:0:3

RUN FOR PLI - 259
	SUCCESS
LAP 260 TIME -> 0:0:1

RUN FOR PSH - 260
	SUCCESS
LAP 261 TIME -> 0:0:0

RUN FOR PNL - 261
	SUCCESS
LAP 262 TIME -> 0:0:1

RUN FOR PFC - 262
	SUCCESS
LAP 263 TIME -> 0:0:1

RUN FOR PETS - 263
	SUCCESS
LAP 264 TIME -> 0:0:0

RUN FOR PTEC - 264
	SUCCESS
LAP 265 TIME -> 0:0:1

RUN FOR PLUS - 265
	SUCCESS
LAP 266 TIME -> 0:0:0

RUN FOR PCT - 266
	SUCCESS
LAP 267 TIME -> 0:0:1

RUN FOR PLP - 267
	SUCCESS
LAP 268 TIME -> 0:0:0

RUN FOR PPH - 268
	SUCCESS
LAP 269 TIME -> 0:0:1

RUN FOR PMO - 269
	SUCCESS
LAP 270 TIME -> 0:0:3

RUN FOR PHP - 270
	SUCCESS
LAP 271 TIME -> 0:0:2

RUN FOR PFG - 271
	SUCCESS
LAP 272 TIME -> 0:0:2

RUN FOR PRTC - 272
	SUCCESS
LAP 273 TIME -> 0:0:0

RUN FOR PZC - 273
	SUCCESS
LAP 274 TIME -> 0:0:2

RUN FOR QQ - 274
	SUCCESS
LAP 275 TIME -> 0:0:1

RUN FOR QLT - 275
	SUCCESS
LAP 276 TIME -> 0:0:0

RUN FOR RNK - 276
	SUCCESS
LAP 277 TIME -> 0:0:2

RUN FOR RAT - 277
	SUCCESS
LAP 278 TIME -> 0:0:2

RUN FOR RDW - 278
	SUCCESS
LAP 279 TIME -> 0:0:2

RUN FOR TRIG - 279
	SUCCESS
LAP 280 TIME -> 0:0:0

RUN FOR RSW - 280
	SUCCESS
LAP 281 TIME -> 0:0:2

RUN FOR RTN - 281
	SUCCESS
LAP 282 TIME -> 0:0:2

RUN FOR RHIM - 282
	SUCCESS
LAP 283 TIME -> 0:0:0

RUN FOR RCP - 283
	SUCCESS
LAP 284 TIME -> 0:0:0

RUN FOR RSE - 284
	SUCCESS
LAP 285 TIME -> 0:0:0

RUN FOR ROR - 285
	SUCCESS
LAP 286 TIME -> 0:0:2

RUN FOR RMG - 286
	SUCCESS
LAP 287 TIME -> 0:0:0

RUN FOR SBRE - 287
	SUCCESS
LAP 288 TIME -> 0:0:0

RUN FOR SAFE - 288
	SUCCESS
LAP 289 TIME -> 0:0:1

RUN FOR SNN - 289
	SUCCESS
LAP 290 TIME -> 0:0:0

RUN FOR SVS - 290
	SUCCESS
LAP 291 TIME -> 0:0:3

RUN FOR SDP - 291
	SUCCESS
LAP 292 TIME -> 0:0:1

RUN FOR SOI - 292
	SUCCESS
LAP 293 TIME -> 0:0:1

RUN FOR SCIN - 293
	SUCCESS
LAP 294 TIME -> 0:0:1

RUN FOR SNR - 294
	SUCCESS
LAP 295 TIME -> 0:0:3

RUN FOR SEQI - 295
	SUCCESS
LAP 296 TIME -> 0:0:0

RUN FOR SRP - 296
	SUCCESS
LAP 297 TIME -> 0:0:2

RUN FOR SHB - 297
	SUCCESS
LAP 298 TIME -> 0:0:2

RUN FOR SHI - 298
	SUCCESS
LAP 299 TIME -> 0:0:3

RUN FOR SRE - 299
	SUCCESS
LAP 300 TIME -> 0:0:1

RUN FOR SSON - 300
	SUCCESS
LAP 301 TIME -> 0:0:0

RUN FOR SCT - 301
	SUCCESS
LAP 302 TIME -> 0:0:0

RUN FOR SOPH - 302
	SUCCESS
LAP 303 TIME -> 0:0:0

RUN FOR SXS - 303
	SUCCESS
LAP 304 TIME -> 0:0:3

RUN FOR SPT - 304
	SUCCESS
LAP 305 TIME -> 0:0:2

RUN FOR SPD - 305
	SUCCESS
LAP 306 TIME -> 0:0:1

RUN FOR SSPG - 306
	SUCCESS
LAP 307 TIME -> 0:0:0

RUN FOR SMP - 307
	SUCCESS
LAP 308 TIME -> 0:0:3

RUN FOR SGC - 308
	SUCCESS
LAP 309 TIME -> 0:0:2

RUN FOR SYNC - 309
	SUCCESS
LAP 310 TIME -> 0:0:0

RUN FOR SYNT - 310
	SUCCESS
LAP 311 TIME -> 0:0:3

RUN FOR TALK - 311
	SUCCESS
LAP 312 TIME -> 0:0:1

RUN FOR TATE - 312
	SUCCESS
LAP 313 TIME -> 0:0:2

RUN FOR TBCG - 313
	SUCCESS
LAP 314 TIME -> 0:0:0

RUN FOR TEP - 314
	SUCCESS
LAP 315 TIME -> 0:0:2

RUN FOR TMPL - 315
	SUCCESS
LAP 316 TIME -> 0:0:1

RUN FOR TEM - 316
	SUCCESS
LAP 317 TIME -> 0:0:1

RUN FOR TIFS - 317
	SUCCESS
LAP 318 TIME -> 0:0:0

RUN FOR TCAP - 318
	SUCCESS
LAP 319 TIME -> 0:0:2

RUN FOR TRY - 319
	SUCCESS
LAP 320 TIME -> 0:0:1

RUN FOR TPK - 320
	SUCCESS
LAP 321 TIME -> 0:0:2

RUN FOR BBOX - 321
	SUCCESS
LAP 322 TIME -> 0:0:0

RUN FOR TLW - 322
	SUCCESS
LAP 323 TIME -> 0:0:2

RUN FOR UDG - 323
	SUCCESS
LAP 324 TIME -> 0:0:2

RUN FOR UKCM - 324
	SUCCESS
LAP 325 TIME -> 0:0:1

RUN FOR ULE - 325
	SUCCESS
LAP 326 TIME -> 0:0:2

RUN FOR UTG - 326
	SUCCESS
LAP 327 TIME -> 0:0:0

RUN FOR VSVS - 327
	SUCCESS
LAP 328 TIME -> 0:0:2

RUN FOR VCT - 328
	SUCCESS
LAP 329 TIME -> 0:0:2

RUN FOR VEIL - 329
	SUCCESS
LAP 330 TIME -> 0:0:0

RUN FOR VOF - 330
	SUCCESS
LAP 331 TIME -> 0:0:1

RUN FOR VVO - 331
	SUCCESS
LAP 332 TIME -> 0:0:0

RUN FOR WEIR - 332

	SUCCESS
LAP 333 TIME -> 0:0:3

RUN FOR JDW - 333
	SUCCESS
LAP 334 TIME -> 0:0:3

RUN FOR SMWH - 334
	SUCCESS
LAP 335 TIME -> 0:0:1

RUN FOR WMH - 335
	SUCCESS
LAP 336 TIME -> 0:0:2

RUN FOR WTAN - 336
	SUCCESS
LAP 337 TIME -> 0:0:1

RUN FOR WIZZ - 337
	SUCCESS
LAP 338 TIME -> 0:0:0

RUN FOR WG - 338
	SUCCESS
LAP 339 TIME -> 0:0:2

RUN FOR WKP - 339
	SUCCESS
LAP 340 TIME -> 0:0:2

RUN FOR WWH - 340
	SUCCESS
LAP 341 TIME -> 0:0:1
TOTAL ELAPSED TIME -> 0:11:12


COMPLETED - ERRORS ENCOUNTERED -> 0

In [12]:
#Get in-row price change
def calc_changes(_s_in,_prev_s_in):
    """Function used to calculate the change between two values, absolute and percentage
    
    args:
    -----
    _s_in - pandas series - the current value to be compared
    _prev_s_in - pandas series - the base value to compare the values to
    
    returns:
    ------
    tuple - pandas series, pandas series - absolute change, percentage change
    """
    _s_change = _s_in - _prev_s_in
    _s_per_change = _s_change / _s_in
    return (_s_change,_s_per_change)

#Relabel col names
for col in df_prices_w:
    df_prices_w.rename(columns={col:col.lower()},inplace=True)
    
df_prices_w["change_price"],df_prices_w["per_change_price"] = calc_changes(df_prices_w.close.copy(),df_prices_w.open.copy())
df_prices_w.head()

,ticker,date,high,low,volume,open,close,change,ema12,ema26,macd_line,signal_line,macd,open_orig,close_orig,high_orig,low_orig,volume_orig,change_price,per_change_price
128355,III,2007-12-31,NaN,NaN,NaN,NaN,NaN,-30.0,NaN,NaN,NaN,NaN,NaN,995.0,965.0,1023.0,964.0,4511565.0,NaN,NaN
128356,III,2008-01-07,0.000000,0.000000,1.000000,0.000000,0.000000,-43.5,NaN,NaN,NaN,NaN,NaN,967.5,924.0,989.0,917.5,16056554.0,0.000000,NaN
128357,III,2008-01-14,0.000000,0.000000,1.000000,0.000000,0.000000,-16.0,NaN,NaN,NaN,NaN,NaN,917.0,901.0,936.0,881.0,21691287.0,0.000000,NaN
128358,III,2008-01-21,0.333333,0.000000,0.776440,0.000000,0.257812,26.5,NaN,NaN,NaN,NaN,NaN,891.0,917.5,965.0,847.0,17850580.0,0.257812,1.000000
128359,III,2008-01-28,0.402299,0.478632,0.440501,0.192308,0.937500,50.0,NaN,NaN,NaN,NaN,NaN,911.0,961.0,971.0,903.0,12079245.0,0.745192,0.794872

In [13]:
df_prices_w = df_prices_w.sort_values(['ticker','date'],ascending=[True,True])
df_prices_w.reset_index(inplace=True,drop=True)
print(df_prices_w.ticker.unique())
df_prices_w.head()

['3IN' '888' 'AAL' 'ABF' 'ADM' 'AGK' 'AGR' 'AHT' 'AJB' 'AML' 'ANTO' 'APAX'
 'ASCL' 'ASHM' 'ASL' 'ATST' 'AUTO' 'AV' 'AVST' 'AVV' 'AZN' 'BA' 'BAB'
 'BAG' 'BAKK' 'BARC' 'BATS' 'BBGI' 'BBOX' 'BBY' 'BDEV' 'BEZ' 'BGEO' 'BGFD'
 'BGSC' 'BHP' 'BKG' 'BLND' 'BME' 'BNKR' 'BNZL' 'BOY' 'BP' 'BRBY' 'BRSC'
 'BRW' 'BRWM' 'BT-A' 'BVIC' 'BVS' 'BWY' 'BYG' 'CAPC' 'CARD' 'CBG' 'CCC'
 'CCH' 'CCL' 'CEY' 'CINE' 'CKN' 'CLDN' 'CLI' 'CNA' 'CNE' 'COA' 'COB' 'CPG'
 'CPI' 'CRDA' 'CRH' 'CRST' 'CSP' 'CTEC' 'CTY' 'CWK' 'DC' 'DCC' 'DGE'
 'DIGS' 'DJAN' 'DLG' 'DLN' 'DNLM' 'DOM' 'DPH' 'DPLM' 'DRX' 'ECM' 'EDIN'
 'EIG' 'ELM' 'EMG' 'ENOG' 'EQN' 'ERM' 'ESNT' 'ETO' 'EVR' 'EXPN' 'EZJ'
 'FCIT' 'FCSS' 'FDM' 'FERG' 'FEV' 'FGP' 'FGT' 'FOUR' 'FRES' 'FSFL' 'FSJ'
 'FSV' 'FUTR' 'FXPO' 'GAW' 'GCP' 'GFRD' 'GFS' 'GFTU' 'GLEN' 'GLO' 'GNC'
 'GNS' 'GOG' 'GPOR' 'GRG' 'GRI' 'GSK' 'GSS' 'GVC' 'HAS' 'HFG' 'HGT' 'HICL'
 'HIK' 'HILS' 'HL' 'HLMA' 'HMSO' 'HOC' 'HRI' 'HSBA' 'HSL' 'HSTG' 'HSV'
 'HSX' 'HTG' 'HVPE' 'HWDN' 'IAG' 'IBST' 'ICGT' 'ICP' 'IGG' 'IHG' 'IHP'
 'III' 'IMB' 'IMI' 'INCH' 'INF' 'INPP' 'INVP' 'IPO' 'ITRK' 'ITV' 'IWG'
 'JAM' 'JD' 'JDW' 'JE' 'JEO' 'JFJ' 'JII' 'JLG' 'JMAT' 'JMG' 'JUP' 'KAZ'
 'KGF' 'KNOS' 'LAND' 'LGEN' 'LLOY' 'LMP' 'LRE' 'LSE' 'LWDB' 'MAB' 'MARS'
 'MCRO' 'MCS' 'MDC' 'MGAM' 'MGGT' 'MKS' 'MNDI' 'MNKS' 'MONY' 'MRC' 'MRO'
 'MRW' 'MSLH' 'MYI' 'NBLS' 'NESF' 'NETW' 'NEX' 'NG' 'NMC' 'NRR' 'NXT'
 'OCDO' 'OSB' 'OXIG' 'PAG' 'PAGE' 'PAY' 'PCT' 'PETS' 'PFC' 'PFG' 'PHNX'
 'PHP' 'PIN' 'PLI' 'PLP' 'PLUS' 'PMO' 'PNL' 'PNN' 'POLY' 'PPH' 'PRTC'
 'PRU' 'PSH' 'PSN' 'PSON' 'PTEC' 'PZC' 'QLT' 'QQ' 'RAT' 'RB' 'RBS' 'RCP'
 'RDSA' 'RDSB' 'RDW' 'REL' 'RHIM' 'RIO' 'RMG' 'RMV' 'RNK' 'ROR' 'RR' 'RSA'
 'RSE' 'RSW' 'RTN' 'RTO' 'SAFE' 'SBRE' 'SBRY' 'SCIN' 'SCT' 'SDP' 'SDR'
 'SEQI' 'SGC' 'SGE' 'SGRO' 'SHB' 'SHI' 'SKG' 'SLA' 'SMDS' 'SMIN' 'SMP'
 'SMT' 'SMWH' 'SN' 'SNN' 'SNR' 'SOI' 'SOPH' 'SPD' 'SPT' 'SPX' 'SRE' 'SRP'
 'SSE' 'SSON' 'SSPG' 'STAN' 'STJ' 'SVS' 'SVT' 'SXS' 'SYNC' 'SYNT' 'TALK'
 'TATE' 'TBCG' 'TCAP' 'TEM' 'TEP' 'TIFS' 'TLW' 'TMPL' 'TPK' 'TRIG' 'TRY'
 'TSCO' 'TUI' 'TW' 'UDG' 'UKCM' 'UKW' 'ULE' 'ULVR' 'UTG' 'UU' 'VCT' 'VEIL'
 'VOD' 'VOF' 'VSVS' 'VVO' 'WEIR' 'WG' 'WIZZ' 'WKP' 'WMH' 'WPP' 'WTAN'
 'WTB' 'WWH']

,ticker,date,high,low,volume,open,close,change,ema12,ema26,macd_line,signal_line,macd,open_orig,close_orig,high_orig,low_orig,volume_orig,change_price,per_change_price
0,3IN,2007-12-31,NaN,NaN,NaN,NaN,NaN,-1.75,NaN,NaN,NaN,NaN,NaN,149.18,147.43,149.89,147.07,1373801.0,NaN,NaN
1,3IN,2008-01-07,0.0,NaN,1.000000,0.000000,1.0,1.76,NaN,NaN,NaN,NaN,NaN,147.07,148.83,149.54,147.07,2345191.0,1.000000,1.000000
2,3IN,2008-01-14,1.0,1.0,0.799111,0.668246,1.0,0.70,NaN,NaN,NaN,NaN,NaN,148.48,149.18,150.59,147.43,2150049.0,0.331754,0.331754
3,3IN,2008-01-21,1.0,0.0,1.000000,0.336493,1.0,4.22,NaN,NaN,NaN,NaN,NaN,147.78,152.00,154.82,145.32,3070968.0,0.663507,0.663507
4,3IN,2008-01-28,1.0,1.0,0.670041,1.000000,1.0,2.11,NaN,NaN,NaN,NaN,NaN,149.89,152.00,154.82,148.83,2510972.0,0.000000,0.000000

# Create buy signals, and sell signals
I am classifying a stock worth buying if it meets all the below criteria:
- The target price (previous max) is hit within x (set as variable target_price_period) periods proceeding this period
- The target price is an increase of x% (set as variable min_gain) over the proceeding day's open price
- There is a drop in the closing price of less x% (set as variable max_drop) between this period and the x periods proceeding this period

I am classifying the sell signals as:
- The close price dips below the target price (previous max) x (set as variable target_price_period) periods proceeding this period
- There is an increase in the closing price of less x% (set as variable max_drop) over the next x periods

In [14]:
#Define the variables for buy sell signals
target_price_period = 12
min_gain = 0.1
max_drop = -0.05

In [15]:
#Programming note
#df.shift(1) looks 1 period into the past
#df.shift(-1) looks 1 period into the future

In [16]:
#Calc a column for will the price increase next week
df_prices_w['signal'] = (df_prices_w.close.shift(-target_price_period) - df_prices_w.close) > 0

print('df_prices_w.signal.value_counts() -> \n{}'.format(df_prices_w.signal.value_counts()))

df_prices_w.signal.value_counts() ->
True     140742
False    139225
Name: signal, dtype: int64

# Create additional features

In [17]:
#Define the variables for additional features
period_high_volatility = 5
period_low_volatility = 3
gap_high_volatility = 3
gap_low_volatility = 2

In [18]:
#Mark minimums and maximums
def flag_mins(_s_in,_period:int=3,_gap:int=3,_cur:bool=False):
    """Function used to identify values in a series as mins
    
    args:
    -----
    _s_in - pandas series - values to be compared
    _period - int:3 - window to check values over
    _gap - int:3 - the number of period which must have elapsed before a min is 
        identified (prevents changing of min_flags on current week vs same week next week)
    _cur - bool:False - is this looking at current or past values
    
    returns:
    ------
    pandas series - bools
    """
    _s_out = 0
    #Create a benchmark series
    _bench_s = _s_in.shift(_gap)
    #Check within window
    for i in range(1,_period+1):
        _s_out += (_bench_s > _bench_s.shift(i)) | (_bench_s.shift(i).isnull())
    #Check within gap
    for i in range(1,_gap+1):
        _s_out += (_bench_s > _bench_s.shift(-i))
    _s_out = _s_out == 0
    return _s_out
def flag_maxs(_s_in,_period:int=3,_gap:int=3,_cur:bool=False):
    """Function used to identify values in a series as maxs
    
    args:
    -----
    _s_in - pandas series - values to be compared
    _period - int:3 - window to check values over
    _gap - int:3 - the number of period which must have elapsed before a min is 
        identified (prevents changing of min_flags on current week vs same week next week)
    _cur - bool:False - is this looking at current or past values
    
    returns:
    ------
    pandas series - bools
    """
    _s_out = 0
    #Create a benchmark series
    _bench_s = _s_in.shift(_gap)
    #Check within window
    for i in range(1,_period+1):
        _s_out += (_bench_s < _bench_s.shift(i)) | (_bench_s.shift(i).isnull())
    #Check within gap
    for i in range(1,_gap+1):
        _s_out += (_bench_s < _bench_s.shift(-i))
    _s_out = _s_out == 0
    return _s_out

In [19]:
#Function to find last max and mins
def prev_max_min(_df_in,_var_col,_bool_col,_gap:int=0):
    """Function to find last max and mins
    
    args:
    -----
    _df_in - pandas dataframe - must contain 'date', _var_col and _bool_col as column names
    _var_col - str - the name of the column containing the current variables
    _bool_col - str - the name of the column containing the bool values defining max and min vlaues
    _gap - int:0 - the number of period which must have elapsed before a min is 
        identified (prevents changing of min_flags on current week vs same week next week)
    
    returns:
    ------
    tuple - pandas series,pandas series - last max/min value, last max/min date
    """
    _df_in["prev_val"] = _df_in.loc[_df_in[_bool_col].shift(-_gap).fillna(False),_var_col]
    _df_in["prev_val"] = _df_in["prev_val"].fillna(method='ffill')
    _df_in["prev_marker_date"] = _df_in.loc[_df_in[_bool_col].shift(-_gap).fillna(False),"date"]
    _df_in["prev_marker_date"] = _df_in["prev_marker_date"].fillna(method='ffill')
    return (_df_in["prev_val"],_df_in["prev_marker_date"])

In [20]:
#Function for finding the gradient of a variable overa set period
def gradient(_s_in,_period:int=1):
    """Function for finding the gradient of a variable over a set period
    
    args:
    -----
    _s_in - pandas series - the series from which the gradient will be found
    _period - int:1 - the period over which the gradient will be found
    
    returns:
    ------
    pandas series
    """
    _s_out = _s_in - _s_in.shift(_period)
    return _s_out

In [21]:
#Calc vol as proportion of previous n-rows
def calc_prop_of_prev(_s_in,_periods:int = 4):
    """Function to this value as a proportion of the cum previous values
    
    args:
    -----
    _s_in - pandas series - values to be looked at
    _period - int - window to sum values over
    
    returns:
    ------
    pandas series - floats
    """
    _s_cum = _s_in.copy()
    for i in range(1,_periods):
        _s_cum += _s_in.shift(i)
    return _s_in / _s_cum

In [22]:
#Mark points of macd positive entry
def pos_entry(_s_in):
    """Function to check if this value is a new positive after a negative value
    
    args:
    -----
    _s_in - pandas series - values to be looked at
    
    returns:
    ------
    pandas series - bools
    """
    return (_s_in > _s_in.shift(1)) & (_s_in > 0) & (_s_in.shift(1) < 0)
def neg_entry(_s_in):
    """Function to check if this value is a new negative after a positive value
    
    args:
    -----
    _s_in - pandas series - values to be looked at
    
    returns:
    ------
    pandas series - bools
    """
    return (_s_in < _s_in.shift(1)) & (_s_in < 0) & (_s_in.shift(1) > 0)

In [23]:
#Function to normalise current price compared to another
def norm_s(_s_in):
    """Function to normalise current price compared to another
    
    args:
    -----
    _s_in - pandas series - values to be looked at
    
    returns:
    ------
    pandas series - bools
    """
    _s_out = (_s_in - _s_in.min()) / (_max_in - _s_in.max())
    return _s_out

In [24]:
#Create separate columns for pos and neg values - allows for normalisation
def pos_neg_cols(_s_in,_gt_lt = "GT"):
    """Function to separate columns for pos and neg values - allows for normalisation
    
    args:
    -----
    _s_in - pandas series - the vlaues ot be looked at
    _gt_lt - str:'GT' - defines if looking for positive or negative values
    
    returns:
    ------
    tuple - pandas series,pandas series - bools,floats
    """
    if _gt_lt.upper() == "GT":
        _bool_s = _s_in >= 0
    elif _gt_lt.upper() == "LT":
        _bool_s = _s_in <= 0
    _df_out = _s_in.to_frame()
    _df_out["_s_in"] = _s_in
    _df_out["_val"] = abs(_s_in[_bool_s])
    _val_s = _df_out["_val"].fillna(0,method=None)
    return (_bool_s,_val_s)

In [88]:
#Function for finding the max within a given time period using indexes
def max_min_period(_s_in,_period:int=1,_normalise:bool=False,_max_min:str='max'):
    """Function for calculating the max and mins within a period
    
    args:
    -----
    _s_in - pandas series - the vlaues to be looked at
    _period - int:1 - the time window to look over
    _max_min - str:max - looking for the max or min
    _normalise - bool:False - should the returned value be normalised?
    
    returns:
    ------
    pandas series - floats
    """
    #Find the min index
    _min_i = _s_in.index.min()
    if _normalise:
        _s_max = pd.Series([_s_in.loc[x-_period if x-_period >= _min_i else _min_i:x].max() for x in _s_in.index])
        _s_min = pd.Series([_s_in.loc[x-_period if x-_period >= _min_i else _min_i:x].min() for x in _s_in.index])
        _s_out = pd.Series((_s_in - _s_min) / (_s_max - _s_min))
    else:
        #Get the max or min within a time period, ensuring not to go into negative indexes
        if _max_min == 'max':
            _s_out = pd.Series([_s_in.loc[x-_period if x-_period >= _min_i else _min_i:x].max() for x in _s_in.index])
        elif _max_min == 'min':
            _s_out = pd.Series([_s_in.loc[x-_period if x-_period >= _min_i else _min_i:x].min() for x in _s_in.index])
        else:
            raise ValueError('_max_min must be either \'max\' or \'min\'')
    _s_out.index = _s_in.index
    return _s_out

In [87]:
#Function for calculating the percentage change within a range
def per_change_in_range(_s_in,_period:int=1,**kwargs):
    """Function for calculating the percentage change of a value from it's max or min within a range
    
    args:
    -----
    _s_in - pandas series - the values to be looked at
    _period - int:1 - the time window to look over
    
    returns:
    ------
    pandas series - floats
    """
    return ((_s_in - max_min_period(_s_in,_period,_normalise=False,**kwargs)) / max_min_period(_s_in,_period,_normalise=False,**kwargs))

In [ ]:
def mk_prev_move_float(_s_in):
    """Function to find the the magnitude of the most recent value change.
    
    args:
    ------
    _s_in - pandas series - float values
    
    returns:
    ------
    pandas series - float values
    """
    _s_out = _s_in - _s_in.shift(1)
    _s_out[_s_out == 0] = np.nan
    _s_out = _s_out.fillna(method='ffill')
    return _s_out

def mk_prev_move_date(_s_in,_periods:int=7):
    """Function to find the time elapsed between two different changes.
    
    args:
    ------
    _s_in - pandas dataframe - datetime values
    _periods - int:7 - used to modify days of datetime into the period required
    
    
    returns:
    ------
    pandas series - int values
    """
    _s_out = _s_in - _s_in.shift(1)
    _s_check = pd.Series([np.floor(_x.days) for _x in _s_out])
    _s_check[_s_check == 0] = np.nan
    _s_check = _s_check.fillna(method='ffill')
    _s_check = [np.floor(_x/_periods) for _x in _s_check]
    return _s_check
#Create features for the cumulative sequential count of max/mins in a certain direction
def mk_move_cum(_s_in):
    """Function for counting the number of changes of the same sign sequentially.
    EG how many positive moves have there been in a row.
    
    args:
    ------
    _s_in - pandas series - floats
    
    returns:
    pandas series - floats
    """
    _li_out = []
    _prev_x = None
    #Loop through each value in _s_in
    for _i,_x in _s_in.iteritems():
        if np.isnan(_x) or _prev_x == None: #If this is the first value add it to the list
            _li_out.append(0)
        else:
            _prev_x = _prev_x if not np.isnan(_prev_x) else 0
            if ((_x < 0) & (_prev_x > 0)) or ((_x > 0) & (_prev_x < 0)): #If a sign change then reset to 0
                _li_out.append(0)
            else:
                if _prev_x != _x: #if there has been a change in value from this and the previous value increment it by 1
                    if _x > 0: #for positive value increment by 1
                        _li_out.append(_li_out[-1] + 1)                                    
                    else: #for negative values increment by -1
                        _li_out.append(_li_out[-1] - 1)
                else: #Otherwise just use the last added value
                    _li_out.append(_li_out[-1])
        _prev_x = _x
    return _li_out
#Create features showing the value change since the first min/max
def mk_long_prev_move_float(_ref_s,_val_s):
    """Function to find the value change since the first max/min move in the current sequential series.
    
    args:
    ------
    _ref_s - pandas series - the reference series from which changes will be detected
    _val_s - pandas series - the values series from which outputs will be created
    
    returns:
    ------
    pandas series - float values
    """
    _li_out = []
    _st_x = None
    _prev_x = None
    #Loop through each value in _s_in
    for _i,_x in _ref_s.iteritems():
        if np.isnan(_x) or _prev_x == None: #If this is the first value add it to the list
            _li_out.append(0)
        else:
            _prev_x = _prev_x if not np.isnan(_prev_x) else 0
            if ((_x < 0) & (_prev_x > 0)) or ((_x > 0) & (_prev_x < 0)): #If a sign change then reset to 0
                _li_out.append(0)
                _st_x = None
            else:
                if _st_x == None: #If _st_x has not been set yet set it to this value
                    _st_x = _val_s[_i]
                _li_out.append(_val_s[_i] - _st_x) #Now calculate the difference and add it to the list
        _prev_x = _x
    return _li_out
def mk_long_prev_move_date(_ref_s,_val_s,_periods:int=7):
    """Function to find the date change since the first max/min move in the current sequential series.
    
    args:
    ------
    _ref_s - pandas series - the reference series from which changes will be detected
    _val_s - pandas series - the values series from which outputs will be created
    _periods - int:7 - used to modify days of datetime into the period required
    
    returns:
    ------
    pandas series - int values
    """
    _li_out = []
    _st_x = None
    _prev_x = None
    #Loop through each value in _s_in
    for _i,_x in _ref_s.iteritems():
        if np.isnan(_x) or _prev_x == None: #If this is the first value add it to the list
            _li_out.append(0)
        else:
            _prev_x = _prev_x if not np.isnan(_prev_x) else 0
            if ((_x < 0) & (_prev_x > 0)) or ((_x > 0) & (_prev_x < 0)): #If a sign change then reset to 0
                _li_out.append(0)
                _st_x = None
            else:
                if _st_x == None: #If _st_x has not been set yet set it to this value
                    _st_x = _val_s[_i]
                _li_out.append(np.floor((_val_s[_i] - _st_x).days/_periods)) #Now calculate the difference and add it to the list
        _prev_x = _x
    return _li_out

In [82]:
#Create a dictionary of max character lengths of fields for use later in h5 file appending
def get_col_len_s(_s_in):
    """Get the max length of value in the series
    
    args:
    -----
    _s_in - pandas series - series holding values to look at for max field lengths
    
    returns:
    ------
    float
    """
    _tmp_s = pd.Series([len(str(x)) for x in _s_in])
    return _tmp_s.max()
    
def get_col_len_df(_df_in):
    """Create a dictionary of max character lengths of fields for use later in h5 file appending
    
    args:
    -----
    _df_in - pandas dataframe - dataframe holding values to look at for max field lengths
    
    returns:
    ------
    pandas series - floats
    """
    _col_lens = {}
    for _c in _df_in:
        _col_lens[_c] = get_col_len_s(_df_in[_c])
    return _col_lens
col_lens = get_col_len_df(df_prices_w)
col_lens

{'ticker': 4,
 'date': 19,
 'high': 22,
 'low': 22,
 'volume': 22,
 'open': 22,
 'close': 22,
 'change': 21,
 'ema12': 22,
 'ema26': 22,
 'macd_line': 23,
 'signal_line': 23,
 'macd': 23,
 'open_orig': 8,
 'close_orig': 8,
 'high_orig': 8,
 'low_orig': 8,
 'volume_orig': 13,
 'change_price': 23,
 'per_change_price': 23,
 'signal': 5}

In [28]:
#Create a single function to run each stock through feature creation
def create_features(_df_in):
    """A single function to run each stock through feature creation
    
    args:
    -----
    _df_in - pandas dataframe
    
    returns:
    ------
    pandas dataframe
    """
    
    _df_out = _df_in.copy() 
    
    #Calc vol as proportion of previous n-rows
    _df_out["prop_vol"] = calc_prop_of_prev(_df_out["volume"].copy().astype("float"),6)

    #Get period-period changes
    for col in ['close','volume','macd','ema26','signal_line','macd_line']:
        _df_out["change_{}_shift1".format(col)] = gradient(_df_out[col],1)
        
    #Compare close to the max/mins within 4,13,26,52 periods
    for col in ['close_orig','macd_line']:
        for max_min in ['max','min']:
            for period in [4,13,26,52]:
                _df_out["{}_per_change_{}_{}".format(col,max_min,period)] = per_change_in_range(_df_out[col],period,_max_min=max_min)
            
    #Mark points of macd positive entry
    _df_out["macd_pos_ent"] = pos_entry(_df_out["macd"])
    _df_out["macd_neg_ent"] = neg_entry(_df_out["macd"])
    
    #Create max min columns
    def mk_cols_max_min(tmp_df,col,period:int=4,gap:int=2):
        #Historic max mins
        tmp_df["{}_min".format(col)] = flag_mins(tmp_df[col],period,gap)
        tmp_df["{}_max".format(col)] = flag_maxs(tmp_df[col],period,gap)
        
    #Find previous max and mins, then look at:
        # - how many positive or negative moves in a row there has been
        # - what the move since the last (n-1) max/min was
        # - what the gradient is since the last (n-1) max/min
        # - what the move since the first max/min was
        # - what the gradient since the first max/min was
    def mk_cols_prev_max_min(tmp_df,col,period:int=4):
        #GETTING THE MAX/MINS - includes "gap" to account for time lag before declaring something as min/max
        tmp_df["prev_max_{}".format(col)],tmp_df["prev_max_{}_date".format(col)] = prev_max_min(tmp_df[["date",col,"{}_max".format(col)]].copy(),col,"{}_max".format(col))
        tmp_df["prev_min_{}".format(col)],tmp_df["prev_min_{}_date".format(col)] = prev_max_min(tmp_df[["date",col,"{}_min".format(col)]].copy(),col,"{}_min".format(col))
#         #Shift the max min columns by n periods to not leak future information
#         tmp_df["prev_max_{}".format(col)] = tmp_df["prev_max_{}".format(col)].shift(period)
#         tmp_df["prev_min_{}".format(col)] = tmp_df["prev_min_{}".format(col)].shift(period)
#         tmp_df["prev_max_{}_date".format(col)] = tmp_df["prev_max_{}_date".format(col)].shift(period)
#         tmp_df["prev_min_{}_date".format(col)] = tmp_df["prev_min_{}_date".format(col)].shift(period)
        #WHAT WAS THE MOVE SINCE THE LAST (N-1) MAX/MIN
        tmp_df['prev_max_move_{}'.format(col)] = mk_prev_move_float(tmp_df["prev_max_{}".format(col)])
        tmp_df['prev_max_date_move_{}'.format(col)] = mk_prev_move_date(tmp_df["prev_max_{}_date".format(col)])        
        tmp_df['prev_min_move_{}'.format(col)] = mk_prev_move_float(tmp_df["prev_min_{}".format(col)])
        tmp_df['prev_min_date_move_{}'.format(col)] = mk_prev_move_date(tmp_df["prev_min_{}_date".format(col)])
        #WHAT IS THE GRADIENT SINCE THE LAST (N-1) MAX/MIN
        tmp_df['prev_max_grad_{}'.format(col)] = tmp_df['prev_max_move_{}'.format(col)] / tmp_df['prev_max_date_move_{}'.format(col)]
        tmp_df['prev_min_grad_{}'.format(col)] = tmp_df['prev_min_move_{}'.format(col)] / tmp_df['prev_min_date_move_{}'.format(col)]
        #HOW MANY PROGRESSIVE MAX/MINS IN A ROW HAVE THERE BEEN - UP OR DOWN FOR BOTH OPTIONS
        tmp_df['max_move_cum_{}'.format(col)] = mk_move_cum(tmp_df['prev_max_move_{}'.format(col)])
        tmp_df['min_move_cum_{}'.format(col)] = mk_move_cum(tmp_df['prev_min_move_{}'.format(col)])
        #WHAT WAS THE MOVE SINCE THE FIRST (N=0) MAX/MIN
        tmp_df['long_prev_max_move_{}'.format(col)] = mk_long_prev_move_float(tmp_df['prev_max_move_{}'.format(col)],tmp_df['prev_max_{}'.format(col)])
        tmp_df['long_prev_min_move_{}'.format(col)] = mk_long_prev_move_float(tmp_df['prev_min_move_{}'.format(col)],tmp_df['prev_min_{}'.format(col)])
        #WHAT WAS THE TIMEDELTA SINCE THE FIRST (N=0) MAX/MIN
        tmp_df['long_prev_max_move_date_{}'.format(col)] = mk_long_prev_move_date(tmp_df['prev_max_move_{}'.format(col)],tmp_df['prev_max_{}_date'.format(col)])
        tmp_df['long_prev_min_move_date_{}'.format(col)] = mk_long_prev_move_date(tmp_df['prev_min_move_{}'.format(col)],tmp_df['prev_min_{}_date'.format(col)])
        #WHAT IS THE GRADIENT SINCE THE FIRST (N=0) MAX/MIN
        tmp_df['long_max_grad_{}'.format(col)] = tmp_df['long_prev_max_move_{}'.format(col)] / tmp_df['long_prev_max_move_date_{}'.format(col)]
        tmp_df['long_min_grad_{}'.format(col)] = tmp_df['long_prev_min_move_{}'.format(col)] / tmp_df['long_prev_min_move_date_{}'.format(col)]
        #WHAT IS THE MAX MIN CONVERGENCE/DIVERGENCE
        tmp_df['prev_grad_conv_{}'.format(col)] = tmp_df['prev_min_grad_{}'.format(col)] - tmp_df['prev_max_grad_{}'.format(col)]
        tmp_df['long_grad_conv_{}'.format(col)] = tmp_df['long_min_grad_{}'.format(col)] - tmp_df['long_max_grad_{}'.format(col)]
        
    #Calc the value changes and percentage changes of these movements
    def mk_cols_prev_max_min_change(tmp_df,col):
        tmp_df["max_change_{}".format(col)],tmp_df["max_per_change_{}".format(col)] = calc_changes(tmp_df[col].copy(),tmp_df["prev_max_{}".format(col)].copy())
        tmp_df["min_change_{}".format(col)],tmp_df["min_per_change_{}".format(col)] = calc_changes(tmp_df[col].copy(),tmp_df["prev_min_{}".format(col)].copy())
        
    #Mark date change since max and mins and convert to periods
    def mk_cols_prev_max_min_date_change(tmp_df,col,period:int=7):
        tmp_df["prev_max_{}_date_change".format(col)] = tmp_df["date"] - tmp_df["prev_max_{}_date".format(col)]
        tmp_df["prev_min_{}_date_change".format(col)] = tmp_df["date"] - tmp_df["prev_min_{}_date".format(col)]
        #Convert all to period changes
        tmp_df["prev_max_{}_date_change".format(col)] = [np.floor(x.days/period) for x in tmp_df["prev_max_{}_date_change".format(col)]]
        tmp_df["prev_min_{}_date_change".format(col)] = [np.floor(x.days/period) for x in tmp_df["prev_min_{}_date_change".format(col)]]
    
    #Run function for columns - high volatility
    for col in ['close','signal_line','volume']:
        mk_cols_max_min(_df_out,col,period_high_volatility,gap_high_volatility)
        mk_cols_prev_max_min(_df_out,col,period_high_volatility)
        mk_cols_prev_max_min_change(_df_out,col) 
        mk_cols_prev_max_min_date_change(_df_out,col,7)
    #Run function for columns - low volatility
    for col in ['macd','ema26','macd_line']:
        mk_cols_max_min(_df_out,col,period_low_volatility,gap_low_volatility)
        mk_cols_prev_max_min(_df_out,col,period_low_volatility)
        mk_cols_prev_max_min_change(_df_out,col) 
        mk_cols_prev_max_min_date_change(_df_out,col,7)
    
    return _df_out

In [86]:
this_tick_df

,ticker,date,high,low,volume,open,close,change,ema12,ema26,...,long_max_grad_macd_line,long_min_grad_macd_line,prev_grad_conv_macd_line,long_grad_conv_macd_line,max_change_macd_line,max_per_change_macd_line,min_change_macd_line,min_per_change_macd_line,prev_max_macd_line_date_change,prev_min_macd_line_date_change
6698,AJB,2018-12-03,NaN,NaN,NaN,NaN,NaN,58.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6699,AJB,2018-12-10,1.000000,1.000000,0.000000,1.000000,1.000000,10.05,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6700,AJB,2018-12-17,0.625000,1.000000,0.000000,1.000000,1.000000,6.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6701,AJB,2018-12-24,0.666667,1.000000,0.000000,1.000000,0.940625,-0.95,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6702,AJB,2018-12-31,1.000000,0.940397,0.052129,0.959459,1.000000,18.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6703,AJB,2019-01-07,1.000000,1.000000,0.370448,1.000000,1.000000,21.95,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6704,AJB,2019-01-14,1.000000,1.000000,1.000000,1.000000,1.000000,15.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6705,AJB,2019-01-21,0.906667,0.862500,0.772510,1.000000,0.714286,-17.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6706,AJB,2019-01-28,0.671333,0.861111,0.368060,0.848000,0.528571,-11.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6707,AJB,2019-02-04,0.690667,0.862500,0.314283,0.745200,0.744286,16.95,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6708,AJB,2019-02-11,0.910667,1.000000,0.353072,0.940000,0.787143,-4.40,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6709,AJB,2019-02-18,1.000000,1.000000,0.663733,0.899200,0.988571,14.80,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6710,AJB,2019-02-25,1.000000,1.000000,0.196457,1.000000,0.989286,-11.20,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6711,AJB,2019-03-04,0.941792,0.985138,0.270377,0.837848,1.000000,14.35,0.907823,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6712,AJB,2019-03-11,1.000000,0.954565,1.000000,0.941134,1.000000,7.00,0.907823,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6713,AJB,2019-03-18,1.000000,1.000000,0.174028,0.988805,1.000000,7.10,0.907823,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6714,AJB,2019-03-25,1.000000,1.000000,0.199557,0.988082,1.000000,23.20,0.912010,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6715,AJB,2019-04-01,1.000000,1.000000,0.127315,1.000000,1.000000,20.00,0.912010,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6716,AJB,2019-04-08,1.000000,1.000000,0.124423,1.000000,1.000000,6.00,0.912010,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6717,AJB,2019-04-15,0.984615,0.971910,0.090695,1.000000,0.992188,-5.00,0.910808,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6718,AJB,2019-04-22,1.000000,1.000000,0.312174,0.936842,1.000000,67.00,0.931606,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6719,AJB,2019-04-29,1.000000,1.000000,0.204953,1.000000,1.000000,36.00,0.964847,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6720,AJB,2019-05-06,1.000000,1.000000,0.195648,1.000000,1.000000,25.00,0.982879,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6721,AJB,2019-05-13,0.965116,0.857143,0.344801,1.000000,0.810277,-48.00,0.968700,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6722,AJB,2019-05-20,0.864341,0.828571,0.164465,0.868167,0.790514,-12.00,0.953087,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6723,AJB,2019-05-27,0.810078,0.900000,0.241228,0.852090,0.782609,-9.00,0.937855,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6724,AJB,2019-06-03,0.786822,0.778571,0.462987,0.845659,0.750988,-15.00,0.917661,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6725,AJB,2019-06-10,0.751938,0.725000,0.405895,0.823151,0.600791,-46.00,0.876995,0.892770,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6726,AJB,2019-06-17,0.658915,0.732143,0.674452,0.678457,0.660079,14.00,0.857967,0.882945,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6727,AJB,2019-06-24,0.686047,0.778571,0.203837,0.704180,0.715415,20.00,0.842512,0.874939,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6728,AJB,2019-07-01,0.709302,0.814286,0.135314,0.755627,0.679842,-5.00,0.816972,0.864283,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6729,AJB,2019-07-08,0.740310,0.796429,0.209918,0.717042,0.762846,28.00,0.807167,0.859030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6730,AJB,2019-07-15,0.829457,0.871429,0.372501,0.784566,0.806324,18.00,0.797684,0.853805,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6731,AJB,2019-07-22,0.930233,0.890357,0.253648,0.842444,0.830040,6.00,0.787676,0.848664,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6732,AJB,2019-07-29,0.819767,0.832000,0.284712,0.829582,0.733202,-14.50,0.760794,0.845614,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6733,AJB,2019-08-05,0.717054,0.746179,0.149205,0.794212,0.640316,-27.00,0.727691,0.846021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6734,AJB,2019-08-12,0.674264,0.754500,0.152079,0.686495,0.644269,7.50,0.716314,0.842611,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6735,AJB,2019-08-19,0.641434,0.739464,0.071522,0.697749,0.604743,-6.00,0.699921,0.834595,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6736,AJB,2019-08-26,0.720930,0.760143,0.218824,0.694534,0.711462,22.00,0.703798,0.828831,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6737,AJB,2019-09-02,0.726744,0.832143,0.194295,0.749196,0.737154,11.50,0.704964,0.820840,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,-0.000000,NaN,0.0
6738,AJB,2019-09-09,0.751938,0.836036,0.266020,0.805466,0.764822,1.00,0.718836,0.813529,...,NaN,NaN,NaN,NaN,NaN,NaN,0.021183,-0.223703,NaN,1.0
6739,AJB,2019-09-16,0.761783,0.850000,1.000000,0.807074,0.774704,3.00,0.727741,0.805885,...,NaN,NaN,NaN,NaN,NaN,NaN,0.037732,-0.482857,NaN,2.0
6740,AJB,2019-09-23,0.765504,0.849679,0.100663,0.823151,0.774704,-2.00,0.731922,0.797862,...,NaN,NaN,NaN,NaN,NaN,NaN,0.049936,-0.757300,NaN,3.0
6741,AJB,2019-09-30,0.755814,0.739286,0.082332,0.803859,0.679842,-20.00,0.724017,0.782812,...,NaN,NaN,NaN,NaN,NaN,NaN,0.057081,-0.970856,NaN,4.0
6742,AJB,2019-10-07,0.670543,0.615071,0.125756,0.755627,0.577075,-31.00,0.702354,0.763798,...,NaN,NaN,NaN,NaN,NaN,NaN,0.054432,-0.885883,NaN,5.0
6743,AJB,2019-10-14,0.639535,0.650071,0.122207,0.655949,0.662055,21.50,0.699263,0.755031,...,NaN,NaN,NaN,NaN,NaN,NaN,0.060108,-1.077807,NaN,6.0
6744,AJB,2019-10-21,0.707364,0.721429,0.257283,0.691318,0.592885,-7.00,0.676776,0.738151,...,NaN,NaN,NaN,NaN,NaN,NaN,0.054502,-0.888018,NaN,7.0
6745,AJB,2019-10-28,0.653101,0.730393,0.111981,0.673633,0.652174,13.50,0.676003,0.728044,...,NaN,NaN,NaN,NaN,NaN,NaN,0.063836,-1.226646,NaN,8.0
6746,AJB,2019-11-04,0.753876,0.759464,0.097815,0.744373,0.681818,-1.00,0.681400,0.717853,...,NaN,NaN,NaN,NaN,NaN,NaN,0.079423,-2.178798,NaN,9.0
6747,AJB,2019-11-11,0.695736,0.791071,0.041095,0.741158,0.703557,5.50,0.687392,0.708132,...,NaN,NaN,NaN,NaN,NaN,NaN,0.095137,-4.587169,NaN,10.0
6748,AJB,2019-11-18,0.730620,0.801786,0.052735,0.728296,0.697628,8.00,0.693448,0.703892,...,NaN,NaN,NaN,NaN,NaN,NaN,0.105432,-10.094521,NaN,11.0
6749,AJB,2019-11-25,0.720930,0.812357,0.247869,0.758842,0.723320,5.00,0.696425,0.702488,...,NaN,NaN,NaN,NaN,NaN,NaN,0.109814,-18.113384,NaN,12.0
6750,AJB,2019-12-02,0.788760,0.788214,0.145144,0.778135,0.703557,-6.00,0.692409,0.698912,...,NaN,NaN,NaN,NaN,NaN,NaN,0.109373,-16.818473,NaN,13.0
6751,AJB,2019-12-09,0.893411,0.817857,0.796860,0.762058,0.790514,21.00,0.701467,0.703664,...,NaN,NaN,NaN,NaN,0.0,-0.0,0.113679,-51.736287,0.0,14.0

In [29]:
#Define the columns for the output
out_cols = [
    #NON-NORMALISED COLS
    "ticker"
    ,"date"
    #NORMALISED COLS
    #Standard features
    ,"open"
    ,"close"
    ,"high"
    ,"low"
    ,"volume"
    ,"change_price"
    ,"per_change_price"
    ,"ema26"
    ,"macd"
    ,"signal_line"
    ,"macd_line"
]
#Append additional columns for key areas
for col in ['close_orig','macd_line']:
    for max_min in ['max','min']:
        for period in [4,13,26,52]:
            out_cols.append("{}_per_change_{}_{}".format(col,max_min,period))
for col in ['close','macd','ema26','signal_line','macd_line','volume']:
    #Shifted features
    out_cols.append("change_{}_shift1".format(col))
    #Max/min flags
    out_cols.append("{}_max".format(col))    
    out_cols.append("{}_min".format(col))    
    #Prev max/min features
    out_cols.append("prev_max_{}".format(col))
    out_cols.append("prev_min_{}".format(col))
    #date changes
    out_cols.append("prev_max_{}_date_change".format(col))
    out_cols.append("prev_min_{}_date_change".format(col))
    #Min max change features
    out_cols.append("max_change_{}".format(col))
    out_cols.append("min_change_{}".format(col))
    #prev max/mins (n-1) - compared to previous
    out_cols.append('prev_max_grad_{}'.format(col))
    out_cols.append('prev_min_grad_{}'.format(col))
    out_cols.append('prev_grad_conv_{}'.format(col))
    #prev max/mins (n=0) - compared to first in this run
    out_cols.append('max_move_cum_{}'.format(col))
    out_cols.append('min_move_cum_{}'.format(col))
    out_cols.append('long_prev_max_move_date_{}'.format(col))
    out_cols.append('long_prev_min_move_date_{}'.format(col))
    out_cols.append('long_max_grad_{}'.format(col))
    out_cols.append('long_min_grad_{}'.format(col))
    out_cols.append('long_grad_conv_{}'.format(col))
#Append signal
out_cols.append("signal")

In [30]:
#A conversion for all variables ot the correct dtype
conv_di = {
    #NON-NORMALISED COLS
    "ticker":'object'
    ,"date":'datetime64'
    #NORMALISED COLS
    #Standard features
    ,"open":'float64'
    ,"close":'float64'
    ,"high":'float64'
    ,"low":'float64'
    ,"volume":'float64'
    ,"change_price":'float64'
    ,"per_change_price":'float64'
    ,"ema26":'float64'
    ,"macd":'float64'
    ,"signal_line":'float64'
    ,"macd_line":'float64'
}
#Append additional columns for key areas
for col in ['close_orig','macd_line']:
    for max_min in ['max','min']:
        for period in [4,13,26,52]:
            conv_di["{}_per_change_{}_{}".format(col,max_min,period)] = 'float64'
for col in ['close','macd','ema26','signal_line','macd_line','volume']:
    #Shifted features
    conv_di["change_{}_shift1".format(col)] = 'float64'
    #Max/min flags
    conv_di["{}_max".format(col)] = 'bool'
    conv_di["{}_min".format(col)] = 'bool'
    #Prev max/min features
    conv_di["prev_max_{}".format(col)] = 'float64'
    conv_di["prev_min_{}".format(col)] = 'float64'
    #date changes
    conv_di["prev_max_{}_date_change".format(col)] = 'float64'
    conv_di["prev_min_{}_date_change".format(col)] = 'float64'
    #Min max change features
    conv_di["max_change_{}".format(col)] = 'float64'
    conv_di["min_change_{}".format(col)] = 'float64'
    #prev max/mins (n-1) - compared to previous
    conv_di['prev_max_grad_{}'.format(col)] = 'float64'
    conv_di['prev_min_grad_{}'.format(col)] = 'float64'
    conv_di['prev_grad_conv_{}'.format(col)] = 'float64'
    #prev max/mins (n=0) - compared to first in this run
    conv_di['max_move_cum_{}'.format(col)] = 'int64'
    conv_di['min_move_cum_{}'.format(col)] = 'int64'
    conv_di['long_prev_max_move_date_{}'.format(col)] = 'float64'
    conv_di['long_prev_min_move_date_{}'.format(col)] = 'float64'
    conv_di['long_max_grad_{}'.format(col)] = 'float64'
    conv_di['long_min_grad_{}'.format(col)] = 'float64'
    conv_di['long_grad_conv_{}'.format(col)] = 'float64'
#Append signal
conv_di["signal"] = 'object'

In [85]:
#Then loop the tickers and combine these into one large dataset
hf_store_name = path+r'\all_hist_prices_w_ft_eng2_TMP.h5'
h_store = pd.HDFStore(hf_store_name)
errors = []
run_time = process_time()
# for tick in tick_ftse["ticker"]:
for tick in ['SBRY','AJB']: #TEMP
    try:
        print("\n{}".format(len(run_time.lap_li)))
        print("RUN FOR {}".format(tick))
        #Isolate this ticker
        this_tick_df = df_prices_w[df_prices_w["ticker"] == re.sub('[^a-zA-Z0-9\-]','',tick)].copy()
        print("shape before -> {}".format(this_tick_df.shape))
        #Create the features
        this_tick_df = create_features(this_tick_df)
        #Clarify col_lens with cur cols in data
        this_col_lens = get_col_len_df(this_tick_df)
        min_itemsize_di = {}
        for col in out_cols:
            if col in col_lens:
                if this_col_lens[col] > col_lens[col]:
                    col_lens[col] = this_col_lens[col]
            else:
                col_lens[col] = this_col_lens[col]
            min_itemsize_di = col_lens[col]
        print("shape after -> {}".format(this_tick_df.shape))
        #Create function for appending to hdf file
        def append_to_hdf(df_in):
            df_in[out_cols].to_hdf(hf_store_name,key='weekly_data',append=True,min_itemsize=min_itemsize_di)
        #Append this data to the group
        try:
            append_to_hdf(this_tick_df)
            print('ADDED TO {}'.format(hf_store_name))
        except ValueError:
            print('WARNING -> Attempting to change dtypes')
            #Try changing the dtypes
            try:
                for col in out_cols:
                    # print(r'CONVERT {} FROM {} TO {}'.format(col,this_tick_df[col].dtype,conv_di[col]))
                    this_tick_df[col] = this_tick_df[col].astype(conv_di[col])
                append_to_hdf(this_tick_df)
                print('ADDED TO {}'.format(hf_store_name))
            except Exception as e:
                errors.append({"ticker":tick,"Error":e})
                print('ERROR READING TO FILE {}'.format(e))
        except Exception as e:
            errors.append({"ticker":tick,"Error":e})
            print('ERROR READING TO FILE {}'.format(e))
        #Lap
        run_time.lap()
        run_time.show_latest_lap_time()
    except Exception as e:
        h_store.close()
        errors.append({"ticker":tick,"Error":e})
        print('ERROR PROCESSING DATA {}'.format(e))
h_store.close()
print('\n\n')
run_time.end()
print('\nERROR COUNT -> {}'.format(len(errors)))
if len(errors) > 0:
    print('\tERRORS -> ')
    display(pd.DataFrame(errors))

0
RUN FOR SBRY
shape before -> (1266, 21)
_s_out 0       467.50
1       468.63
2       468.63
3       487.73
4       487.73
         ...
1261    216.20
1262    214.40
1263    214.40
1264    220.00
1265    223.20
Length: 1266, dtype: float64
_s_out 0       467.50
1       468.63
2       468.63
3       487.73
4       487.73
         ...
1261    216.20
1262    214.40
1263    214.40
1264    220.00
1265    223.20
Length: 1266, dtype: float64
_s_out 0       467.50
1       468.63
2       468.63
3       487.73
4       487.73
         ...
1261    222.50
1262    222.50
1263    222.50
1264    222.50
1265    223.20
Length: 1266, dtype: float64
_s_out 0       467.50
1       468.63
2       468.63
3       487.73
4       487.73
         ...
1261    222.50
1262    222.50
1263    222.50
1264    222.50
1265    223.20
Length: 1266, dtype: float64
_s_out 0       467.50
1       468.63
2       468.63
3       487.73
4       487.73
         ...
1261    222.50
1262    222.50
1263    222.50
1264    222.50
1265    223.20
Length: 1266, dtype: float64
_s_out 0       467.50
1       468.63
2       468.63
3       487.73
4       487.73
         ...
1261    222.50
1262    222.50
1263    222.50
1264    222.50
1265    223.20
Length: 1266, dtype: float64
_s_out 0       467.50
1       468.63
2       468.63
3       487.73
4       487.73
         ...
1261    310.30
1262    310.30
1263    305.00
1264    300.00
1265    291.90
Length: 1266, dtype: float64
_s_out 0       467.50
1       468.63
2       468.63
3       487.73
4       487.73
         ...
1261    310.30
1262    310.30
1263    305.00
1264    300.00
1265    291.90
Length: 1266, dtype: float64
_period 4
_min_i 214063
_s_in 214063    467.50
214064    468.63
214065    468.63
214066    487.73
214067    484.36
           ...
215324    204.80
215325    214.40
215326    214.30
215327    220.00
215328    223.20
Name: close_orig, Length: 1266, dtype: float64
_s_out 0       467.5
1       467.5
2       467.5
3       467.5
4       467.5
        ...
1261    201.0
1262    201.0
1263    201.0
1264    201.0
1265    204.8
Length: 1266, dtype: float64
_period 4
_min_i 214063
_s_in 214063    467.50
214064    468.63
214065    468.63
214066    487.73
214067    484.36
           ...
215324    204.80
215325    214.40
215326    214.30
215327    220.00
215328    223.20
Name: close_orig, Length: 1266, dtype: float64
_s_out 0       467.5
1       467.5
2       467.5
3       467.5
4       467.5
        ...
1261    201.0
1262    201.0
1263    201.0
1264    201.0
1265    204.8
Length: 1266, dtype: float64
_period 13
_min_i 214063
_s_in 214063    467.50
214064    468.63
214065    468.63
214066    487.73
214067    484.36
           ...
215324    204.80
215325    214.40
215326    214.30
215327    220.00
215328    223.20
Name: close_orig, Length: 1266, dtype: float64
_s_out 0       467.5
1       467.5
2       467.5
3       467.5
4       467.5
        ...
1261    182.5
1262    196.1
1263    196.1
1264    201.0
1265    201.0
Length: 1266, dtype: float64
_period 13
_min_i 214063
_s_in 214063    467.50
214064    468.63
214065    468.63
214066    487.73
214067    484.36
           ...
215324    204.80
215325    214.40
215326    214.30
215327    220.00
215328    223.20
Name: close_orig, Length: 1266, dtype: float64
_s_out 0       467.5
1       467.5
2       467.5
3       467.5
4       467.5
        ...
1261    182.5
1262    196.1
1263    196.1
1264    201.0
1265    201.0
Length: 1266, dtype: float64
_period 26
_min_i 214063
_s_in 214063    467.50
214064    468.63
214065    468.63
214066    487.73
214067    484.36
           ...
215324    204.80
215325    214.40
215326    214.30
215327    220.00
215328    223.20
Name: close_orig, Length: 1266, dtype: float64
_s_out 0       467.5
1       467.5
2       467.5
3       467.5
4       467.5
        ...
1261    182.5
1262    182.5
1263    182.5
1264    182.5
1265    182.5
Length: 1266, dtype: float64
_period 26
_min_i 214063
_s_in 214063    467.50
214064    468.63
214065    468.63
214066    487.73
214067    484.36
           ...
215324    204.80
215325    214.40
215326    214.30
215327    220.00
215328    223.20
Name: close_orig, Length: 1266, dtype: float64
_s_out 0       467.5
1       467.5
2       467.5
3       467.5
4       467.5
        ...
1261    182.5
1262    182.5
1263    182.5
1264    182.5
1265    182.5
Length: 1266, dtype: float64
_period 52
_min_i 214063
_s_in 214063    467.50
214064    468.63
214065    468.63
214066    487.73
214067    484.36
           ...
215324    204.80
215325    214.40
215326    214.30
215327    220.00
215328    223.20
Name: close_orig, Length: 1266, dtype: float64
_s_out 0       467.5
1       467.5
2       467.5
3       467.5
4       467.5
        ...
1261    182.5
1262    182.5
1263    182.5
1264    182.5
1265    182.5
Length: 1266, dtype: float64
_period 52
_min_i 214063
_s_in 214063    467.50
214064    468.63
214065    468.63
214066    487.73
214067    484.36
           ...
215324    204.80
215325    214.40
215326    214.30
215327    220.00
215328    223.20
Name: close_orig, Length: 1266, dtype: float64
_s_out 0       467.5
1       467.5
2       467.5
3       467.5
4       467.5
        ...
1261    182.5
1262    182.5
1263    182.5
1264    182.5
1265    182.5
Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261    0.073229
1262    0.076710
1263    0.077661
1264    0.080287
1265    0.080287
Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261    0.073229
1262    0.076710
1263    0.077661
1264    0.080287
1265    0.080287
Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261    0.073229
1262    0.076710
1263    0.077661
1264    0.080287
1265    0.080287
Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261    0.073229
1262    0.076710
1263    0.077661
1264    0.080287
1265    0.080287
Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261    0.073229
1262    0.076710
1263    0.077661
1264    0.080287
1265    0.080287
Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261    0.073229
1262    0.076710
1263    0.077661
1264    0.080287
1265    0.080287
Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261    0.073229
1262    0.076710
1263    0.077661
1264    0.080287
1265    0.080287
Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261    0.073229
1262    0.076710
1263    0.077661
1264    0.080287
1265    0.080287
Length: 1266, dtype: float64
_period 4
_min_i 214063
_s_in 214063         NaN
214064         NaN
214065         NaN
214066         NaN
214067         NaN
            ...
215324    0.073229
215325    0.076710
215326    0.077661
215327    0.080287
215328    0.073157
Name: macd_line, Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261    0.057810
1262    0.061846
1263    0.063895
1264    0.067064
1265    0.073157
Length: 1266, dtype: float64
_period 4
_min_i 214063
_s_in 214063         NaN
214064         NaN
214065         NaN
214066         NaN
214067         NaN
            ...
215324    0.073229
215325    0.076710
215326    0.077661
215327    0.080287
215328    0.073157
Name: macd_line, Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261    0.057810
1262    0.061846
1263    0.063895
1264    0.067064
1265    0.073157
Length: 1266, dtype: float64
_period 13
_min_i 214063
_s_in 214063         NaN
214064         NaN
214065         NaN
214066         NaN
214067         NaN
            ...
215324    0.073229
215325    0.076710
215326    0.077661
215327    0.080287
215328    0.073157
Name: macd_line, Length: 1266, dtype: float64

_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261   -0.014997
1262    0.004401
1263    0.006749
1264    0.013154
1265    0.027749
Length: 1266, dtype: float64
_period 13
_min_i 214063
_s_in 214063         NaN
214064         NaN
214065         NaN
214066         NaN
214067         NaN
            ...
215324    0.073229
215325    0.076710
215326    0.077661
215327    0.080287
215328    0.073157
Name: macd_line, Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261   -0.014997
1262    0.004401
1263    0.006749
1264    0.013154
1265    0.027749
Length: 1266, dtype: float64
_period 26
_min_i 214063
_s_in 214063         NaN
214064         NaN
214065         NaN
214066         NaN
214067         NaN
            ...
215324    0.073229
215325    0.076710
215326    0.077661
215327    0.080287
215328    0.073157
Name: macd_line, Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261   -0.150946
1262   -0.138980
1263   -0.122652
1264   -0.107388
1265   -0.093415
Length: 1266, dtype: float64
_period 26
_min_i 214063
_s_in 214063         NaN
214064         NaN
214065         NaN
214066         NaN
214067         NaN
            ...
215324    0.073229
215325    0.076710
215326    0.077661
215327    0.080287
215328    0.073157
Name: macd_line, Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261   -0.150946
1262   -0.138980
1263   -0.122652
1264   -0.107388
1265   -0.093415
Length: 1266, dtype: float64
_period 52
_min_i 214063
_s_in 214063         NaN
214064         NaN
214065         NaN
214066         NaN
214067         NaN
            ...
215324    0.073229
215325    0.076710
215326    0.077661
215327    0.080287
215328    0.073157
Name: macd_line, Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261   -0.150946
1262   -0.150946
1263   -0.150946
1264   -0.150946
1265   -0.150946
Length: 1266, dtype: float64
_period 52
_min_i 214063
_s_in 214063         NaN
214064         NaN
214065         NaN
214066         NaN
214067         NaN
            ...
215324    0.073229
215325    0.076710
215326    0.077661
215327    0.080287
215328    0.073157
Name: macd_line, Length: 1266, dtype: float64
_s_out 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
1261   -0.150946
1262   -0.150946
1263   -0.150946
1264   -0.150946
1265   -0.150946
Length: 1266, dtype: float64
shape after -> (1266, 214)
ADDED TO C:\Users\Robert\Documents\python_scripts\stock_trading_ml_modelling\historical_prices\all_hist_prices_w_ft_eng2_TMP.h5
LAP 1 TIME -> 0:0:18

1
RUN FOR AJB
shape before -> (54, 21)
_s_out 0     220.00
1     235.00
2     236.00
3     236.00
4     251.00
5     273.95
6     290.00
7     290.00
8     290.00
9     290.00
10    290.00
11    289.20
12    289.25
13    292.35
14    299.30
15    306.00
16    322.00
17    342.00
18    348.00
19    348.00
20    407.00
21    448.00
22    473.00
23    473.00
24    473.00
25    473.00
26    473.00
27    425.00
28    420.00
29    418.00
30    410.00
31    413.00
32    424.00
33    430.00
34    430.00
35    430.00
36    430.00
37    430.00
38    405.50
39    406.50
40    413.50
41    416.00
42    416.00
43    416.00
44    416.00
45    416.00
46    416.00
47    392.00
48    392.50
49    398.00
50    398.00
51    403.00
52    403.00
53    420.00
dtype: float64
_s_out 0     220.00
1     235.00
2     236.00
3     236.00
4     251.00
5     273.95
6     290.00
7     290.00
8     290.00
9     290.00
10    290.00
11    289.20
12    289.25
13    292.35
14    299.30
15    306.00
16    322.00
17    342.00
18    348.00
19    348.00
20    407.00
21    448.00
22    473.00
23    473.00
24    473.00
25    473.00
26    473.00
27    425.00
28    420.00
29    418.00
30    410.00
31    413.00
32    424.00
33    430.00
34    430.00
35    430.00
36    430.00
37    430.00
38    405.50
39    406.50
40    413.50
41    416.00
42    416.00
43    416.00
44    416.00
45    416.00
46    416.00
47    392.00
48    392.50
49    398.00
50    398.00
51    403.00
52    403.00
53    420.00
dtype: float64
_s_out 0     220.00
1     235.00
2     236.00
3     236.00
4     251.00
5     273.95
6     290.00
7     290.00
8     290.00
9     290.00
10    290.00
11    290.00
12    290.00
13    292.35
14    299.30
15    306.00
16    322.00
17    342.00
18    348.00
19    348.00
20    407.00
21    448.00
22    473.00
23    473.00
24    473.00
25    473.00
26    473.00
27    473.00
28    473.00
29    473.00
30    473.00
31    473.00
32    473.00
33    473.00
34    473.00
35    473.00
36    430.00
37    430.00
38    430.00
39    430.00
40    430.00
41    430.00
42    430.00
43    430.00
44    430.00
45    430.00
46    430.00
47    416.00
48    416.00
49    416.00
50    416.00
51    416.00
52    416.00
53    420.00
dtype: float64
_s_out 0     220.00
1     235.00
2     236.00
3     236.00
4     251.00
5     273.95
6     290.00
7     290.00
8     290.00
9     290.00
10    290.00
11    290.00
12    290.00
13    292.35
14    299.30
15    306.00
16    322.00
17    342.00
18    348.00
19    348.00
20    407.00
21    448.00
22    473.00
23    473.00
24    473.00
25    473.00
26    473.00
27    473.00
28    473.00
29    473.00
30    473.00
31    473.00
32    473.00
33    473.00
34    473.00
35    473.00
36    430.00
37    430.00
38    430.00
39    430.00
40    430.00
41    430.00
42    430.00
43    430.00
44    430.00
45    430.00
46    430.00
47    416.00
48    416.00
49    416.00
50    416.00
51    416.00
52    416.00
53    420.00
dtype: float64
_s_out 0     220.00
1     235.00
2     236.00
3     236.00
4     251.00
5     273.95
6     290.00
7     290.00
8     290.00
9     290.00
10    290.00
11    290.00
12    290.00
13    292.35
14    299.30
15    306.00
16    322.00
17    342.00
18    348.00
19    348.00
20    407.00
21    448.00
22    473.00
23    473.00
24    473.00
25    473.00
26    473.00
27    473.00
28    473.00
29    473.00
30    473.00
31    473.00
32    473.00
33    473.00
34    473.00
35    473.00
36    473.00
37    473.00
38    473.00
39    473.00
40    473.00
41    473.00
42    473.00
43    473.00
44    473.00
45    473.00
46    473.00
47    473.00
48    473.00
49    430.00
50    430.00
51    430.00
52    430.00
53    430.00
dtype: float64
_s_out 0     220.00
1     235.00
2     236.00
3     236.00
4     251.00
5     273.95
6     290.00
7     290.00
8     290.00
9     290.00
10    290.00
11    290.00
12    290.00
13    292.35
14    299.30
15    306.00
16    322.00
17    342.00
18    348.00
19    348.00
20    407.00
21    448.00
22    473.00
23    473.00
24    473.00
25    473.00
26    473.00
27    473.00
28    473.00
29    473.00
30    473.00
31    473.00
32    473.00
33    473.00
34    473.00
35    473.00
36    473.00
37    473.00
38    473.00
39    473.00
40    473.00
41    473.00
42    473.00
43    473.00
44    473.00
45    473.00
46    473.00
47    473.00
48    473.00
49    430.00
50    430.00
51    430.00
52    430.00
53    430.00
dtype: float64
_s_out 0     220.00
1     235.00
2     236.00
3     236.00
4     251.00
5     273.95
6     290.00
7     290.00
8     290.00
9     290.00
10    290.00
11    290.00
12    290.00
13    292.35
14    299.30
15    306.00
16    322.00
17    342.00
18    348.00
19    348.00
20    407.00
21    448.00
22    473.00
23    473.00
24    473.00
25    473.00
26    473.00
27    473.00
28    473.00
29    473.00
30    473.00
31    473.00
32    473.00
33    473.00
34    473.00
35    473.00
36    473.00
37    473.00
38    473.00
39    473.00
40    473.00
41    473.00
42    473.00
43    473.00
44    473.00
45    473.00
46    473.00
47    473.00
48    473.00
49    473.00
50    473.00
51    473.00
52    473.00
53    473.00
dtype: float64
_s_out 0     220.00
1     235.00
2     236.00
3     236.00
4     251.00
5     273.95
6     290.00
7     290.00
8     290.00
9     290.00
10    290.00
11    290.00
12    290.00
13    292.35
14    299.30
15    306.00
16    322.00
17    342.00
18    348.00
19    348.00
20    407.00
21    448.00
22    473.00
23    473.00
24    473.00
25    473.00
26    473.00
27    473.00
28    473.00
29    473.00
30    473.00
31    473.00
32    473.00
33    473.00
34    473.00
35    473.00
36    473.00
37    473.00
38    473.00
39    473.00
40    473.00
41    473.00
42    473.00
43    473.00
44    473.00
45    473.00
46    473.00
47    473.00
48    473.00
49    473.00
50    473.00
51    473.00
52    473.00
53    473.00
dtype: float64

_period 4
_min_i 6698
_s_in 6698    220.00
6699    235.00
6700    236.00
6701    235.05
6702    251.00
6703    273.95
6704    290.00
6705    270.00
6706    257.00
6707    272.10
6708    275.10
6709    289.20
6710    289.25
6711    292.35
6712    299.30
6713    306.00
6714    322.00
6715    342.00
6716    348.00
6717    347.00
6718    407.00
6719    448.00
6720    473.00
6721    425.00
6722    420.00
6723    418.00
6724    410.00
6725    372.00
6726    387.00
6727    401.00
6728    392.00
6729    413.00
6730    424.00
6731    430.00
6732    405.50
6733    382.00
6734    383.00
6735    373.00
6736    400.00
6737    406.50
6738    413.50
6739    416.00
6740    416.00
6741    392.00
6742    366.00
6743    387.50
6744    370.00
6745    385.00
6746    392.50
6747    398.00
6748    396.50
6749    403.00
6750    398.00
6751    420.00
Name: close_orig, dtype: float64
_s_out 0     220.00
1     220.00
2     220.00
3     220.00
4     220.00
5     235.00
6     235.05
7     235.05
8     251.00
9     257.00
10    257.00
11    257.00
12    257.00
13    272.10
14    275.10
15    289.20
16    289.25
17    292.35
18    299.30
19    306.00
20    322.00
21    342.00
22    347.00
23    347.00
24    407.00
25    418.00
26    410.00
27    372.00
28    372.00
29    372.00
30    372.00
31    372.00
32    387.00
33    392.00
34    392.00
35    382.00
36    382.00
37    373.00
38    373.00
39    373.00
40    373.00
41    373.00
42    400.00
43    392.00
44    366.00
45    366.00
46    366.00
47    366.00
48    366.00
49    370.00
50    370.00
51    385.00
52    392.50
53    396.50
dtype: float64
_period 4
_min_i 6698
_s_in 6698    220.00
6699    235.00
6700    236.00
6701    235.05
6702    251.00
6703    273.95
6704    290.00
6705    270.00
6706    257.00
6707    272.10
6708    275.10
6709    289.20
6710    289.25
6711    292.35
6712    299.30
6713    306.00
6714    322.00
6715    342.00
6716    348.00
6717    347.00
6718    407.00
6719    448.00
6720    473.00
6721    425.00
6722    420.00
6723    418.00
6724    410.00
6725    372.00
6726    387.00
6727    401.00
6728    392.00
6729    413.00
6730    424.00
6731    430.00
6732    405.50
6733    382.00
6734    383.00
6735    373.00
6736    400.00
6737    406.50
6738    413.50
6739    416.00
6740    416.00
6741    392.00
6742    366.00
6743    387.50
6744    370.00
6745    385.00
6746    392.50
6747    398.00
6748    396.50
6749    403.00
6750    398.00
6751    420.00
Name: close_orig, dtype: float64
_s_out 0     220.00
1     220.00
2     220.00
3     220.00
4     220.00
5     235.00
6     235.05
7     235.05
8     251.00
9     257.00
10    257.00
11    257.00
12    257.00
13    272.10
14    275.10
15    289.20
16    289.25
17    292.35
18    299.30
19    306.00
20    322.00
21    342.00
22    347.00
23    347.00
24    407.00
25    418.00
26    410.00
27    372.00
28    372.00
29    372.00
30    372.00
31    372.00
32    387.00
33    392.00
34    392.00
35    382.00
36    382.00
37    373.00
38    373.00
39    373.00
40    373.00
41    373.00
42    400.00
43    392.00
44    366.00
45    366.00
46    366.00
47    366.00
48    366.00
49    370.00
50    370.00
51    385.00
52    392.50
53    396.50
dtype: float64
_period 13
_min_i 6698
_s_in 6698    220.00
6699    235.00
6700    236.00
6701    235.05
6702    251.00
6703    273.95
6704    290.00
6705    270.00
6706    257.00
6707    272.10
6708    275.10
6709    289.20
6710    289.25
6711    292.35
6712    299.30
6713    306.00
6714    322.00
6715    342.00
6716    348.00
6717    347.00
6718    407.00
6719    448.00
6720    473.00
6721    425.00
6722    420.00
6723    418.00
6724    410.00
6725    372.00
6726    387.00
6727    401.00
6728    392.00
6729    413.00
6730    424.00
6731    430.00
6732    405.50
6733    382.00
6734    383.00
6735    373.00
6736    400.00
6737    406.50
6738    413.50
6739    416.00
6740    416.00
6741    392.00
6742    366.00
6743    387.50
6744    370.00
6745    385.00
6746    392.50
6747    398.00
6748    396.50
6749    403.00
6750    398.00
6751    420.00
Name: close_orig, dtype: float64
_s_out 0     220.00
1     220.00
2     220.00
3     220.00
4     220.00
5     220.00
6     220.00
7     220.00
8     220.00
9     220.00
10    220.00
11    220.00
12    220.00
13    220.00
14    235.00
15    235.05
16    235.05
17    251.00
18    257.00
19    257.00
20    257.00
21    257.00
22    272.10
23    275.10
24    289.20
25    289.25
26    292.35
27    299.30
28    306.00
29    322.00
30    342.00
31    347.00
32    347.00
33    372.00
34    372.00
35    372.00
36    372.00
37    372.00
38    372.00
39    372.00
40    372.00
41    373.00
42    373.00
43    373.00
44    366.00
45    366.00
46    366.00
47    366.00
48    366.00
49    366.00
50    366.00
51    366.00
52    366.00
53    366.00
dtype: float64
_period 13
_min_i 6698
_s_in 6698    220.00
6699    235.00
6700    236.00
6701    235.05
6702    251.00
6703    273.95
6704    290.00
6705    270.00
6706    257.00
6707    272.10
6708    275.10
6709    289.20
6710    289.25
6711    292.35
6712    299.30
6713    306.00
6714    322.00
6715    342.00
6716    348.00
6717    347.00
6718    407.00
6719    448.00
6720    473.00
6721    425.00
6722    420.00
6723    418.00
6724    410.00
6725    372.00
6726    387.00
6727    401.00
6728    392.00
6729    413.00
6730    424.00
6731    430.00
6732    405.50
6733    382.00
6734    383.00
6735    373.00
6736    400.00
6737    406.50
6738    413.50
6739    416.00
6740    416.00
6741    392.00
6742    366.00
6743    387.50
6744    370.00
6745    385.00
6746    392.50
6747    398.00
6748    396.50
6749    403.00
6750    398.00
6751    420.00
Name: close_orig, dtype: float64
_s_out 0     220.00
1     220.00
2     220.00
3     220.00
4     220.00
5     220.00
6     220.00
7     220.00
8     220.00
9     220.00
10    220.00
11    220.00
12    220.00
13    220.00
14    235.00
15    235.05
16    235.05
17    251.00
18    257.00
19    257.00
20    257.00
21    257.00
22    272.10
23    275.10
24    289.20
25    289.25
26    292.35
27    299.30
28    306.00
29    322.00
30    342.00
31    347.00
32    347.00
33    372.00
34    372.00
35    372.00
36    372.00
37    372.00
38    372.00
39    372.00
40    372.00
41    373.00
42    373.00
43    373.00
44    366.00
45    366.00
46    366.00
47    366.00
48    366.00
49    366.00
50    366.00
51    366.00
52    366.00
53    366.00
dtype: float64
_period 26
_min_i 6698
_s_in 6698    220.00
6699    235.00
6700    236.00
6701    235.05
6702    251.00
6703    273.95
6704    290.00
6705    270.00
6706    257.00
6707    272.10
6708    275.10
6709    289.20
6710    289.25
6711    292.35
6712    299.30
6713    306.00
6714    322.00
6715    342.00
6716    348.00
6717    347.00
6718    407.00
6719    448.00
6720    473.00
6721    425.00
6722    420.00
6723    418.00
6724    410.00
6725    372.00
6726    387.00
6727    401.00
6728    392.00
6729    413.00
6730    424.00
6731    430.00
6732    405.50
6733    382.00
6734    383.00
6735    373.00
6736    400.00
6737    406.50
6738    413.50
6739    416.00
6740    416.00
6741    392.00
6742    366.00
6743    387.50
6744    370.00
6745    385.00
6746    392.50
6747    398.00
6748    396.50
6749    403.00
6750    398.00
6751    420.00
Name: close_orig, dtype: float64
_s_out 0     220.00
1     220.00
2     220.00
3     220.00
4     220.00
5     220.00
6     220.00
7     220.00
8     220.00
9     220.00
10    220.00
11    220.00
12    220.00
13    220.00
14    220.00
15    220.00
16    220.00
17    220.00
18    220.00
19    220.00
20    220.00
21    220.00
22    220.00
23    220.00
24    220.00
25    220.00
26    220.00
27    235.00
28    235.05
29    235.05
30    251.00
31    257.00
32    257.00
33    257.00
34    257.00
35    272.10
36    275.10
37    289.20
38    289.25
39    292.35
40    299.30
41    306.00
42    322.00
43    342.00
44    347.00
45    347.00
46    366.00
47    366.00
48    366.00
49    366.00
50    366.00
51    366.00
52    366.00
53    366.00
dtype: float64
_period 26
_min_i 6698
_s_in 6698    220.00
6699    235.00
6700    236.00
6701    235.05
6702    251.00
6703    273.95
6704    290.00
6705    270.00
6706    257.00
6707    272.10
6708    275.10
6709    289.20
6710    289.25
6711    292.35
6712    299.30
6713    306.00
6714    322.00
6715    342.00
6716    348.00
6717    347.00
6718    407.00
6719    448.00
6720    473.00
6721    425.00
6722    420.00
6723    418.00
6724    410.00
6725    372.00
6726    387.00
6727    401.00
6728    392.00
6729    413.00
6730    424.00
6731    430.00
6732    405.50
6733    382.00
6734    383.00
6735    373.00
6736    400.00
6737    406.50
6738    413.50
6739    416.00
6740    416.00
6741    392.00
6742    366.00
6743    387.50
6744    370.00
6745    385.00
6746    392.50
6747    398.00
6748    396.50
6749    403.00
6750    398.00
6751    420.00
Name: close_orig, dtype: float64
_s_out 0     220.00
1     220.00
2     220.00
3     220.00
4     220.00
5     220.00
6     220.00
7     220.00
8     220.00
9     220.00
10    220.00
11    220.00
12    220.00
13    220.00
14    220.00
15    220.00
16    220.00
17    220.00
18    220.00
19    220.00
20    220.00
21    220.00
22    220.00
23    220.00
24    220.00
25    220.00
26    220.00
27    235.00
28    235.05
29    235.05
30    251.00
31    257.00
32    257.00
33    257.00
34    257.00
35    272.10
36    275.10
37    289.20
38    289.25
39    292.35
40    299.30
41    306.00
42    322.00
43    342.00
44    347.00
45    347.00
46    366.00
47    366.00
48    366.00
49    366.00
50    366.00
51    366.00
52    366.00
53    366.00
dtype: float64
_period 52
_min_i 6698
_s_in 6698    220.00
6699    235.00
6700    236.00
6701    235.05
6702    251.00
6703    273.95
6704    290.00
6705    270.00
6706    257.00
6707    272.10
6708    275.10
6709    289.20
6710    289.25
6711    292.35
6712    299.30
6713    306.00
6714    322.00
6715    342.00
6716    348.00
6717    347.00
6718    407.00
6719    448.00
6720    473.00
6721    425.00
6722    420.00
6723    418.00
6724    410.00
6725    372.00
6726    387.00
6727    401.00
6728    392.00
6729    413.00
6730    424.00
6731    430.00
6732    405.50
6733    382.00
6734    383.00
6735    373.00
6736    400.00
6737    406.50
6738    413.50
6739    416.00
6740    416.00
6741    392.00
6742    366.00
6743    387.50
6744    370.00
6745    385.00
6746    392.50
6747    398.00
6748    396.50
6749    403.00
6750    398.00
6751    420.00
Name: close_orig, dtype: float64
_s_out 0     220.0
1     220.0
2     220.0
3     220.0
4     220.0
5     220.0
6     220.0
7     220.0
8     220.0
9     220.0
10    220.0
11    220.0
12    220.0
13    220.0
14    220.0
15    220.0
16    220.0
17    220.0
18    220.0
19    220.0
20    220.0
21    220.0
22    220.0
23    220.0
24    220.0
25    220.0
26    220.0
27    220.0
28    220.0
29    220.0
30    220.0
31    220.0
32    220.0
33    220.0
34    220.0
35    220.0
36    220.0
37    220.0
38    220.0
39    220.0
40    220.0
41    220.0
42    220.0
43    220.0
44    220.0
45    220.0
46    220.0
47    220.0
48    220.0
49    220.0
50    220.0
51    220.0
52    220.0
53    235.0
dtype: float64
_period 52
_min_i 6698
_s_in 6698    220.00
6699    235.00
6700    236.00
6701    235.05
6702    251.00
6703    273.95
6704    290.00
6705    270.00
6706    257.00
6707    272.10
6708    275.10
6709    289.20
6710    289.25
6711    292.35
6712    299.30
6713    306.00
6714    322.00
6715    342.00
6716    348.00
6717    347.00
6718    407.00
6719    448.00
6720    473.00
6721    425.00
6722    420.00
6723    418.00
6724    410.00
6725    372.00
6726    387.00
6727    401.00
6728    392.00
6729    413.00
6730    424.00
6731    430.00
6732    405.50
6733    382.00
6734    383.00
6735    373.00
6736    400.00
6737    406.50
6738    413.50
6739    416.00
6740    416.00
6741    392.00
6742    366.00
6743    387.50
6744    370.00
6745    385.00
6746    392.50
6747    398.00
6748    396.50
6749    403.00
6750    398.00
6751    420.00
Name: close_orig, dtype: float64
_s_out 0     220.0
1     220.0
2     220.0
3     220.0
4     220.0
5     220.0
6     220.0
7     220.0
8     220.0
9     220.0
10    220.0
11    220.0
12    220.0
13    220.0
14    220.0
15    220.0
16    220.0
17    220.0
18    220.0
19    220.0
20    220.0
21    220.0
22    220.0
23    220.0
24    220.0
25    220.0
26    220.0
27    220.0
28    220.0
29    220.0
30    220.0
31    220.0
32    220.0
33    220.0
34    220.0
35    220.0
36    220.0
37    220.0
38    220.0
39    220.0
40    220.0
41    220.0
42    220.0
43    220.0
44    220.0
45    220.0
46    220.0
47    220.0
48    220.0
49    220.0
50    220.0
51    220.0
52    220.0
53    235.0
dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.015775
29   -0.015775
30   -0.015775
31   -0.015775
32   -0.024978
33   -0.032427
34   -0.047311
35   -0.051863
36   -0.056121
37   -0.060988
38   -0.084820
39   -0.115876
40   -0.094693
41   -0.078144
42   -0.065940
43   -0.058795
44   -0.058795
45   -0.055769
46   -0.055769
47   -0.052041
48   -0.036453
49   -0.020740
50   -0.010444
51   -0.006063
52   -0.006063
53   -0.002197

dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.015775
29   -0.015775
30   -0.015775
31   -0.015775
32   -0.024978
33   -0.032427
34   -0.047311
35   -0.051863
36   -0.056121
37   -0.060988
38   -0.084820
39   -0.115876
40   -0.094693
41   -0.078144
42   -0.065940
43   -0.058795
44   -0.058795
45   -0.055769
46   -0.055769
47   -0.052041
48   -0.036453
49   -0.020740
50   -0.010444
51   -0.006063
52   -0.006063
53   -0.002197
dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.015775
29   -0.015775
30   -0.015775
31   -0.015775
32   -0.015775
33   -0.015775
34   -0.015775
35   -0.015775
36   -0.015775
37   -0.015775
38   -0.015775
39   -0.015775
40   -0.015775
41   -0.024978
42   -0.032427
43   -0.047311
44   -0.051863
45   -0.055769
46   -0.055769
47   -0.052041
48   -0.036453
49   -0.020740
50   -0.010444
51   -0.006063
52   -0.006063
53   -0.002197
dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.015775
29   -0.015775
30   -0.015775
31   -0.015775
32   -0.015775
33   -0.015775
34   -0.015775
35   -0.015775
36   -0.015775
37   -0.015775
38   -0.015775
39   -0.015775
40   -0.015775
41   -0.024978
42   -0.032427
43   -0.047311
44   -0.051863
45   -0.055769
46   -0.055769
47   -0.052041
48   -0.036453
49   -0.020740
50   -0.010444
51   -0.006063
52   -0.006063
53   -0.002197
dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.015775
29   -0.015775
30   -0.015775
31   -0.015775
32   -0.015775
33   -0.015775
34   -0.015775
35   -0.015775
36   -0.015775
37   -0.015775
38   -0.015775
39   -0.015775
40   -0.015775
41   -0.015775
42   -0.015775
43   -0.015775
44   -0.015775
45   -0.015775
46   -0.015775
47   -0.015775
48   -0.015775
49   -0.015775
50   -0.010444
51   -0.006063
52   -0.006063
53   -0.002197
dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.015775
29   -0.015775
30   -0.015775
31   -0.015775
32   -0.015775
33   -0.015775
34   -0.015775
35   -0.015775
36   -0.015775
37   -0.015775
38   -0.015775
39   -0.015775
40   -0.015775
41   -0.015775
42   -0.015775
43   -0.015775
44   -0.015775
45   -0.015775
46   -0.015775
47   -0.015775
48   -0.015775
49   -0.015775
50   -0.010444
51   -0.006063
52   -0.006063
53   -0.002197
dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.015775
29   -0.015775
30   -0.015775
31   -0.015775
32   -0.015775
33   -0.015775
34   -0.015775
35   -0.015775
36   -0.015775
37   -0.015775
38   -0.015775
39   -0.015775
40   -0.015775
41   -0.015775
42   -0.015775
43   -0.015775
44   -0.015775
45   -0.015775
46   -0.015775
47   -0.015775
48   -0.015775
49   -0.015775
50   -0.010444
51   -0.006063
52   -0.006063
53   -0.002197
dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.015775
29   -0.015775
30   -0.015775
31   -0.015775
32   -0.015775
33   -0.015775
34   -0.015775
35   -0.015775
36   -0.015775
37   -0.015775
38   -0.015775
39   -0.015775
40   -0.015775
41   -0.015775
42   -0.015775
43   -0.015775
44   -0.015775
45   -0.015775
46   -0.015775
47   -0.015775
48   -0.015775
49   -0.015775
50   -0.010444
51   -0.006063
52   -0.006063
53   -0.002197
dtype: float64
_period 4
_min_i 6698
_s_in 6698         NaN
6699         NaN
6700         NaN
6701         NaN
6702         NaN
6703         NaN
6704         NaN
6705         NaN
6706         NaN
6707         NaN
6708         NaN
6709         NaN
6710         NaN
6711         NaN
6712         NaN
6713         NaN
6714         NaN
6715         NaN
6716         NaN
6717         NaN
6718         NaN
6719         NaN
6720         NaN
6721         NaN
6722         NaN
6723         NaN
6724         NaN
6725   -0.015775
6726   -0.024978
6727   -0.032427
6728   -0.047311
6729   -0.051863
6730   -0.056121
6731   -0.060988
6732   -0.084820
6733   -0.118330
6734   -0.126296
6735   -0.134673
6736   -0.125033
6737   -0.115876
6738   -0.094693
6739   -0.078144
6740   -0.065940
6741   -0.058795
6742   -0.061444
6743   -0.055769
6744   -0.061375
6745   -0.052041
6746   -0.036453
6747   -0.020740
6748   -0.010444
6749   -0.006063
6750   -0.006503
6751   -0.002197
Name: macd_line, dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.024978
29   -0.032427
30   -0.047311
31   -0.051863
32   -0.056121
33   -0.060988
34   -0.084820
35   -0.118330
36   -0.126296
37   -0.134673
38   -0.134673
39   -0.134673
40   -0.134673
41   -0.134673
42   -0.125033
43   -0.115876
44   -0.094693
45   -0.078144
46   -0.065940
47   -0.061444
48   -0.061444
49   -0.061375
50   -0.061375
51   -0.052041
52   -0.036453
53   -0.020740
dtype: float64
_period 4
_min_i 6698
_s_in 6698         NaN
6699         NaN
6700         NaN
6701         NaN
6702         NaN
6703         NaN
6704         NaN
6705         NaN
6706         NaN
6707         NaN
6708         NaN
6709         NaN
6710         NaN
6711         NaN
6712         NaN
6713         NaN
6714         NaN
6715         NaN
6716         NaN
6717         NaN
6718         NaN
6719         NaN
6720         NaN
6721         NaN
6722         NaN
6723         NaN
6724         NaN
6725   -0.015775
6726   -0.024978
6727   -0.032427
6728   -0.047311
6729   -0.051863
6730   -0.056121
6731   -0.060988
6732   -0.084820
6733   -0.118330
6734   -0.126296
6735   -0.134673
6736   -0.125033
6737   -0.115876
6738   -0.094693
6739   -0.078144
6740   -0.065940
6741   -0.058795
6742   -0.061444
6743   -0.055769
6744   -0.061375
6745   -0.052041
6746   -0.036453
6747   -0.020740
6748   -0.010444
6749   -0.006063
6750   -0.006503
6751   -0.002197
Name: macd_line, dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.024978
29   -0.032427
30   -0.047311
31   -0.051863
32   -0.056121
33   -0.060988
34   -0.084820
35   -0.118330
36   -0.126296
37   -0.134673
38   -0.134673
39   -0.134673
40   -0.134673
41   -0.134673
42   -0.125033
43   -0.115876
44   -0.094693
45   -0.078144
46   -0.065940
47   -0.061444
48   -0.061444
49   -0.061375
50   -0.061375
51   -0.052041
52   -0.036453
53   -0.020740
dtype: float64
_period 13
_min_i 6698
_s_in 6698         NaN
6699         NaN
6700         NaN
6701         NaN
6702         NaN
6703         NaN
6704         NaN
6705         NaN
6706         NaN
6707         NaN
6708         NaN
6709         NaN
6710         NaN
6711         NaN
6712         NaN
6713         NaN
6714         NaN
6715         NaN
6716         NaN
6717         NaN
6718         NaN
6719         NaN
6720         NaN
6721         NaN
6722         NaN
6723         NaN
6724         NaN
6725   -0.015775
6726   -0.024978
6727   -0.032427
6728   -0.047311
6729   -0.051863
6730   -0.056121
6731   -0.060988
6732   -0.084820
6733   -0.118330
6734   -0.126296
6735   -0.134673
6736   -0.125033
6737   -0.115876
6738   -0.094693
6739   -0.078144
6740   -0.065940
6741   -0.058795
6742   -0.061444
6743   -0.055769
6744   -0.061375
6745   -0.052041
6746   -0.036453
6747   -0.020740
6748   -0.010444
6749   -0.006063
6750   -0.006503
6751   -0.002197
Name: macd_line, dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.024978
29   -0.032427
30   -0.047311
31   -0.051863
32   -0.056121
33   -0.060988
34   -0.084820
35   -0.118330
36   -0.126296
37   -0.134673
38   -0.134673
39   -0.134673
40   -0.134673
41   -0.134673
42   -0.134673
43   -0.134673
44   -0.134673
45   -0.134673
46   -0.134673
47   -0.134673
48   -0.134673
49   -0.134673
50   -0.134673
51   -0.125033
52   -0.115876
53   -0.094693
dtype: float64
_period 13
_min_i 6698
_s_in 6698         NaN
6699         NaN
6700         NaN
6701         NaN
6702         NaN
6703         NaN
6704         NaN
6705         NaN
6706         NaN
6707         NaN
6708         NaN
6709         NaN
6710         NaN
6711         NaN
6712         NaN
6713         NaN
6714         NaN
6715         NaN
6716         NaN
6717         NaN
6718         NaN
6719         NaN
6720         NaN
6721         NaN
6722         NaN
6723         NaN
6724         NaN
6725   -0.015775
6726   -0.024978
6727   -0.032427
6728   -0.047311
6729   -0.051863
6730   -0.056121
6731   -0.060988
6732   -0.084820
6733   -0.118330
6734   -0.126296
6735   -0.134673
6736   -0.125033
6737   -0.115876
6738   -0.094693
6739   -0.078144
6740   -0.065940
6741   -0.058795
6742   -0.061444
6743   -0.055769
6744   -0.061375
6745   -0.052041
6746   -0.036453
6747   -0.020740
6748   -0.010444
6749   -0.006063
6750   -0.006503
6751   -0.002197
Name: macd_line, dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.024978
29   -0.032427
30   -0.047311
31   -0.051863
32   -0.056121
33   -0.060988
34   -0.084820
35   -0.118330
36   -0.126296
37   -0.134673
38   -0.134673
39   -0.134673
40   -0.134673
41   -0.134673
42   -0.134673
43   -0.134673
44   -0.134673
45   -0.134673
46   -0.134673
47   -0.134673
48   -0.134673
49   -0.134673
50   -0.134673
51   -0.125033
52   -0.115876
53   -0.094693
dtype: float64
_period 26
_min_i 6698
_s_in 6698         NaN
6699         NaN
6700         NaN
6701         NaN
6702         NaN
6703         NaN
6704         NaN
6705         NaN
6706         NaN
6707         NaN
6708         NaN
6709         NaN
6710         NaN
6711         NaN
6712         NaN
6713         NaN
6714         NaN
6715         NaN
6716         NaN
6717         NaN
6718         NaN
6719         NaN
6720         NaN
6721         NaN
6722         NaN
6723         NaN
6724         NaN
6725   -0.015775
6726   -0.024978
6727   -0.032427
6728   -0.047311
6729   -0.051863
6730   -0.056121
6731   -0.060988
6732   -0.084820
6733   -0.118330
6734   -0.126296
6735   -0.134673
6736   -0.125033
6737   -0.115876
6738   -0.094693
6739   -0.078144
6740   -0.065940
6741   -0.058795
6742   -0.061444
6743   -0.055769
6744   -0.061375
6745   -0.052041
6746   -0.036453
6747   -0.020740
6748   -0.010444
6749   -0.006063
6750   -0.006503
6751   -0.002197
Name: macd_line, dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.024978
29   -0.032427
30   -0.047311
31   -0.051863
32   -0.056121
33   -0.060988
34   -0.084820
35   -0.118330
36   -0.126296
37   -0.134673
38   -0.134673
39   -0.134673
40   -0.134673
41   -0.134673
42   -0.134673
43   -0.134673
44   -0.134673
45   -0.134673
46   -0.134673
47   -0.134673
48   -0.134673
49   -0.134673
50   -0.134673
51   -0.134673
52   -0.134673
53   -0.134673
dtype: float64
_period 26
_min_i 6698
_s_in 6698         NaN
6699         NaN
6700         NaN
6701         NaN
6702         NaN
6703         NaN
6704         NaN
6705         NaN
6706         NaN
6707         NaN
6708         NaN
6709         NaN
6710         NaN
6711         NaN
6712         NaN
6713         NaN
6714         NaN
6715         NaN
6716         NaN
6717         NaN
6718         NaN
6719         NaN
6720         NaN
6721         NaN
6722         NaN
6723         NaN
6724         NaN
6725   -0.015775
6726   -0.024978
6727   -0.032427
6728   -0.047311
6729   -0.051863
6730   -0.056121
6731   -0.060988
6732   -0.084820
6733   -0.118330
6734   -0.126296
6735   -0.134673
6736   -0.125033
6737   -0.115876
6738   -0.094693
6739   -0.078144
6740   -0.065940
6741   -0.058795
6742   -0.061444
6743   -0.055769
6744   -0.061375
6745   -0.052041
6746   -0.036453
6747   -0.020740
6748   -0.010444
6749   -0.006063
6750   -0.006503
6751   -0.002197
Name: macd_line, dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.024978
29   -0.032427
30   -0.047311
31   -0.051863
32   -0.056121
33   -0.060988
34   -0.084820
35   -0.118330
36   -0.126296
37   -0.134673
38   -0.134673
39   -0.134673
40   -0.134673
41   -0.134673
42   -0.134673
43   -0.134673
44   -0.134673
45   -0.134673
46   -0.134673
47   -0.134673
48   -0.134673
49   -0.134673
50   -0.134673
51   -0.134673
52   -0.134673
53   -0.134673
dtype: float64
_period 52
_min_i 6698
_s_in 6698         NaN
6699         NaN
6700         NaN
6701         NaN
6702         NaN
6703         NaN
6704         NaN
6705         NaN
6706         NaN
6707         NaN
6708         NaN
6709         NaN
6710         NaN
6711         NaN
6712         NaN
6713         NaN
6714         NaN
6715         NaN
6716         NaN
6717         NaN
6718         NaN
6719         NaN
6720         NaN
6721         NaN
6722         NaN
6723         NaN
6724         NaN
6725   -0.015775
6726   -0.024978
6727   -0.032427
6728   -0.047311
6729   -0.051863
6730   -0.056121
6731   -0.060988
6732   -0.084820
6733   -0.118330
6734   -0.126296
6735   -0.134673
6736   -0.125033
6737   -0.115876
6738   -0.094693
6739   -0.078144
6740   -0.065940
6741   -0.058795
6742   -0.061444
6743   -0.055769
6744   -0.061375
6745   -0.052041
6746   -0.036453
6747   -0.020740
6748   -0.010444
6749   -0.006063
6750   -0.006503
6751   -0.002197
Name: macd_line, dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.024978
29   -0.032427
30   -0.047311
31   -0.051863
32   -0.056121
33   -0.060988
34   -0.084820
35   -0.118330
36   -0.126296
37   -0.134673
38   -0.134673
39   -0.134673
40   -0.134673
41   -0.134673
42   -0.134673
43   -0.134673
44   -0.134673
45   -0.134673
46   -0.134673
47   -0.134673
48   -0.134673
49   -0.134673
50   -0.134673
51   -0.134673
52   -0.134673
53   -0.134673
dtype: float64
_period 52
_min_i 6698
_s_in 6698         NaN
6699         NaN
6700         NaN
6701         NaN
6702         NaN
6703         NaN
6704         NaN
6705         NaN
6706         NaN
6707         NaN
6708         NaN
6709         NaN
6710         NaN
6711         NaN
6712         NaN
6713         NaN
6714         NaN
6715         NaN
6716         NaN
6717         NaN
6718         NaN
6719         NaN
6720         NaN
6721         NaN
6722         NaN
6723         NaN
6724         NaN
6725   -0.015775
6726   -0.024978
6727   -0.032427
6728   -0.047311
6729   -0.051863
6730   -0.056121
6731   -0.060988
6732   -0.084820
6733   -0.118330
6734   -0.126296
6735   -0.134673
6736   -0.125033
6737   -0.115876
6738   -0.094693
6739   -0.078144
6740   -0.065940
6741   -0.058795
6742   -0.061444
6743   -0.055769
6744   -0.061375
6745   -0.052041
6746   -0.036453
6747   -0.020740
6748   -0.010444
6749   -0.006063
6750   -0.006503
6751   -0.002197
Name: macd_line, dtype: float64
_s_out 0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27   -0.015775
28   -0.024978
29   -0.032427
30   -0.047311
31   -0.051863
32   -0.056121

dtype: float64
shape after -> (54, 214)
WARNING -> Attempting to change dtypes
ERROR READING TO FILE cannot match existing table structure for [ticker] on appending data
LAP 2 TIME -> 0:0:1



TOTAL ELAPSED TIME -> 0:0:19

ERROR COUNT -> 1
	ERRORS ->

  ticker                                              Error
0    AJB  cannot match existing table structure for [tic...

In [32]:
#close any open h5 files
tables.file._open_files.close_all()

In [33]:
tmp_df = pd.read_hdf(hf_store_name,key='weekly_data',mode='r')
print("")
print("FINAL HDFSTORE SIZE: {}".format(tmp_df.shape))
print("FINAL SIGNAL COUNTS: {}".format(tmp_df.signal.value_counts()))
h_store.close()
tmp_df.head(50)
# tmp_df[(tmp_df["ticker"] == 'ADM') & (tmp_df["date"] > '2013-12-01') & (tmp_df["date"] < '2014-02-01')].head(200)

FINAL HDFSTORE SIZE: (279509, 144)
FINAL SIGNAL COUNTS: True     140508
False    139001
Name: signal, dtype: int64

,ticker,date,open,close,high,low,volume,change_price,per_change_price,ema26,...,prev_min_grad_volume,prev_grad_conv_volume,max_move_cum_volume,min_move_cum_volume,long_prev_max_move_date_volume,long_prev_min_move_date_volume,long_max_grad_volume,long_min_grad_volume,long_grad_conv_volume,signal
128355,III,2007-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,False
128356,III,2008-01-07,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,NaN,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,False
128357,III,2008-01-14,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,NaN,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,True
128358,III,2008-01-21,0.000000,0.257812,0.333333,0.000000,0.776440,0.257812,1.000000,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,True
128359,III,2008-01-28,0.192308,0.937500,0.402299,0.478632,0.440501,0.745192,0.794872,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,False
128360,III,2008-02-04,0.759615,0.351562,0.591954,0.581197,0.636501,-0.408053,-1.160684,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,True
128361,III,2008-02-11,0.182692,0.289062,0.120690,0.504274,0.446567,0.106370,0.367983,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,False
128362,III,2008-02-18,0.288462,0.000000,0.275862,0.282051,0.476198,-0.288462,-inf,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,False
128363,III,2008-02-25,0.004808,0.000000,0.000000,0.000000,0.938878,-0.004808,-inf,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,False
128364,III,2008-03-03,0.000000,0.000000,0.000000,0.000000,0.824143,0.000000,NaN,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,False
128365,III,2008-03-10,0.000000,0.000000,0.000000,0.000000,0.654455,0.000000,NaN,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,True
128366,III,2008-03-17,0.000000,0.080605,0.000000,0.000000,0.660293,0.080605,1.000000,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,True
128367,III,2008-03-24,0.202454,0.362720,0.245763,0.315240,0.413488,0.160266,0.441846,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,True
128368,III,2008-03-31,0.343558,0.581864,0.455508,0.373695,0.621723,0.238306,0.409556,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,False
128369,III,2008-04-07,0.562372,0.435768,0.468220,0.511482,0.287221,-0.126604,-0.290530,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,True
128370,III,2008-04-14,0.390593,0.614610,0.461864,0.478079,0.212186,0.224017,0.364486,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,False
128371,III,2008-04-21,0.578732,0.556675,0.451271,0.478079,0.265450,-0.022057,-0.039623,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,False
128372,III,2008-04-28,0.533742,0.491184,0.406780,0.524008,0.210532,-0.042558,-0.086645,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,True
128373,III,2008-05-05,0.468303,0.584383,0.512712,0.505219,0.179288,0.116080,0.198637,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,True
128374,III,2008-05-12,0.554192,0.770781,0.616525,0.530271,0.798383,0.216589,0.280999,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,False
128375,III,2008-05-19,0.715746,0.465995,0.601695,0.561587,0.569271,-0.249751,-0.535953,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,True
128376,III,2008-05-26,0.470348,0.599496,0.500000,0.561587,0.221706,0.129149,0.215429,NaN,...,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,False
128377,III,2008-06-02,0.552147,0.478589,0.453390,0.567850,0.466823,-0.073558,-0.153697,NaN,...,NaN,NaN,-1,0,0.0,0.0,NaN,NaN,NaN,False
128378,III,2008-06-09,0.441718,0.309824,0.330508,0.331942,0.494679,-0.131894,-0.425707,NaN,...,NaN,NaN,-1,0,0.0,0.0,NaN,NaN,NaN,True
128379,III,2008-06-16,0.308793,0.312343,0.271186,0.369520,0.565805,0.003549,0.011363,NaN,...,NaN,NaN,-1,0,0.0,0.0,NaN,NaN,NaN,False
128380,III,2008-06-23,0.286299,0.267003,0.264831,0.356994,0.516996,-0.019296,-0.072269,NaN,...,NaN,NaN,-1,0,0.0,0.0,NaN,NaN,NaN,False
128381,III,2008-06-30,0.261759,0.186398,0.192797,0.294363,0.460547,-0.075361,-0.404300,NaN,...,NaN,NaN,-1,0,0.0,0.0,NaN,NaN,NaN,False
128382,III,2008-07-07,0.237219,0.093199,0.177966,0.219207,0.543214,-0.144020,-1.545294,0.325072,...,NaN,NaN,-1,0,0.0,0.0,NaN,NaN,NaN,True
128383,III,2008-07-14,0.204499,0.765743,0.563559,0.294363,0.672471,0.561244,0.732940,0.378209,...,NaN,NaN,-1,0,0.0,0.0,NaN,NaN,NaN,False
128384,III,2008-07-21,0.672802,0.604534,0.709746,0.578288,0.643902,-0.068268,-0.112926,0.393538,...,NaN,NaN,-1,0,0.0,0.0,NaN,NaN,NaN,True
128385,III,2008-07-28,0.556237,0.705290,0.561441,0.544885,0.260657,0.149052,0.211335,0.413349,...,NaN,NaN,-1,0,0.0,0.0,NaN,NaN,NaN,True
128386,III,2008-08-04,0.656442,0.952141,0.733051,0.724426,0.273814,0.295699,0.310563,0.423365,...,NaN,NaN,-2,0,9.0,0.0,-0.021445,NaN,NaN,False
128387,III,2008-08-11,0.862986,0.717884,0.758475,0.724426,0.158885,-0.145102,-0.202124,0.427400,...,NaN,NaN,-2,0,9.0,0.0,-0.021445,NaN,NaN,False
128388,III,2008-08-18,0.648262,0.617128,0.521186,0.532359,0.118785,-0.031133,-0.050449,0.435209,...,NaN,NaN,-2,0,9.0,0.0,-0.021445,NaN,NaN,True
128389,III,2008-08-25,0.498978,0.770781,0.567797,0.578288,0.150290,0.271803,0.352634,0.468568,...,NaN,NaN,-2,0,9.0,0.0,-0.021445,NaN,NaN,False
128390,III,2008-09-01,0.668712,0.619647,0.669492,0.680585,0.377312,-0.049064,-0.079181,0.484822,...,NaN,NaN,-2,0,9.0,0.0,-0.021445,NaN,NaN,False
128391,III,2008-09-08,0.707566,0.682620,0.675847,0.643006,0.333184,-0.024947,-0.036546,0.511554,...,0.007432,0.028877,-2,1,9.0,0.0,-0.021445,NaN,NaN,False
128392,III,2008-09-15,0.509202,0.405542,0.394068,0.106472,1.000000,-0.103661,-0.255611,0.515339,...,0.007432,0.028877,-2,1,9.0,0.0,-0.021445,NaN,NaN,False
128393,III,2008-09-22,0.496933,0.113350,0.372881,0.246347,0.462561,-0.383582,-3.384049,0.505267,...,0.007432,0.028877,-2,1,9.0,0.0,-0.021445,NaN,NaN,False
128394,III,2008-09-29,0.147239,0.000000,0.010593,0.000000,0.657322,-0.147239,-inf,0.487990,...,0.007432,0.028877,-2,1,9.0,0.0,-0.021445,NaN,NaN,False
128395,III,2008-10-06,0.000000,0.000000,0.000000,0.000000,0.905799,0.000000,NaN,0.467269,...,0.007432,-0.062789,0,1,0.0,0.0,NaN,NaN,NaN,False
128396,III,2008-10-13,0.000000,0.000000,0.000000,0.000000,0.979021,0.000000,NaN,0.451750,...,0.007432,-0.062789,0,1,0.0,0.0,NaN,NaN,NaN,True
128397,III,2008-10-20,0.000000,0.076130,0.000000,0.000000,0.878454,0.076130,1.000000,0.435501,...,0.007432,-0.062789,0,1,0.0,0.0,NaN,NaN,NaN,True
128398,III,2008-10-27,0.000000,0.165029,0.029652,0.016152,0.424401,0.165029,1.000000,0.424973,...,0.007432,-0.062789,0,1,0.0,0.0,NaN,NaN,NaN,False
128399,III,2008-11-03,0.172023,0.047151,0.161554,0.061283,0.501998,-0.124871,-2.648314,0.404626,...,0.007432,-0.062789,0,1,0.0,0.0,NaN,NaN,NaN,False
128400,III,2008-11-10,0.047732,0.000000,0.000000,0.000000,0.423464,-0.047732,-inf,0.382001,...,0.007432,-0.062789,0,1,0.0,0.0,NaN,NaN,NaN,False
128401,III,2008-11-17,0.000000,0.000000,0.000000,0.000000,0.396013,0.000000,NaN,0.354552,...,0.007432,-0.062789,0,1,0.0,0.0,NaN,NaN,NaN,True
128402,III,2008-11-24,0.000000,0.081743,0.047739,0.039527,0.371998,0.081743,1.000000,0.344012,...,0.007432,-0.062789,0,1,0.0,0.0,NaN,NaN,NaN,False
128403,III,2008-12-01,0.063358,0.000000,0.000000,0.000000,0.347933,-0.063358,-inf,0.319518,...,0.007432,-0.062789,0,1,0.0,0.0,NaN,NaN,NaN,False
128404,III,2008-12-08,0.000000,0.000000,0.000000,0.000000,0.647935,0.000000,NaN,0.302474,...,0.007432,-0.062789,0,1,0.0,0.0,NaN,NaN,NaN,False

In [34]:
#close any open h5 files
tables.file._open_files.close_all()

In [35]:
#Delete the old h5 file and rename the TMP
try:
    os.remove(path+r'\all_hist_prices_w_ft_eng2.h5')
    print('\nSUCCESSFULLY REMOVED {}'.format(path+r'\all_hist_prices_w_ft_eng2.h5'))
except Exception as e:
    print('\nERROR - REMOVING:{}'.format(e))
try:
    os.rename(path+r'\all_hist_prices_w_ft_eng2_TMP.h5',path+r'\all_hist_prices_w_ft_eng2.h5')
    print('\nSUCCESSFULLY RENAMED {} TO {}'.format(path+r'\all_hist_prices_w_ft_eng2_TMP.h5',path+r'\all_hist_prices_w_ft_eng2.h5'))
except Exception as e:
    print('\nERROR - RENAMING:{}'.format(e))

SUCCESSFULLY REMOVED C:\Users\Robert\Documents\python_scripts\stock_trading_ml_modelling\historical_prices\all_hist_prices_w_ft_eng2.h5

SUCCESSFULLY RENAMED C:\Users\Robert\Documents\python_scripts\stock_trading_ml_modelling\historical_prices\all_hist_prices_w_ft_eng2_TMP.h5 TO C:\Users\Robert\Documents\python_scripts\stock_trading_ml_modelling\historical_prices\all_hist_prices_w_ft_eng2.h5

In [36]:
#Remove 'date' from out_cols
out_cols.remove('date')

In [37]:
#Export a list of the features for this model
file_object = open(path+r'\feature_engineering_feature_list.txt','w')
feature_str = ''
for i in out_cols:
    feature_str += '{},'.format(i)
feature_str = feature_str[:-1]
file_object.write(feature_str)
file_object.close()
feature_str

'ticker,open,close,high,low,volume,change_price,per_change_price,ema26,macd,signal_line,macd_line,close_orig_per_change_max_4,close_orig_per_change_max_13,close_orig_per_change_max_26,close_orig_per_change_max_52,close_orig_per_change_min_4,close_orig_per_change_min_13,close_orig_per_change_min_26,close_orig_per_change_min_52,macd_line_per_change_max_4,macd_line_per_change_max_13,macd_line_per_change_max_26,macd_line_per_change_max_52,macd_line_per_change_min_4,macd_line_per_change_min_13,macd_line_per_change_min_26,macd_line_per_change_min_52,change_close_shift1,close_max,close_min,prev_max_close,prev_min_close,prev_max_close_date_change,prev_min_close_date_change,max_change_close,min_change_close,prev_max_grad_close,prev_min_grad_close,prev_grad_conv_close,max_move_cum_close,min_move_cum_close,long_prev_max_move_date_close,long_prev_min_move_date_close,long_max_grad_close,long_min_grad_close,long_grad_conv_close,change_macd_shift1,macd_max,macd_min,prev_max_macd,prev_min_macd,prev_max_macd_date_change,prev_min_macd_date_change,max_change_macd,min_change_macd,prev_max_grad_macd,prev_min_grad_macd,prev_grad_conv_macd,max_move_cum_macd,min_move_cum_macd,long_prev_max_move_date_macd,long_prev_min_move_date_macd,long_max_grad_macd,long_min_grad_macd,long_grad_conv_macd,change_ema26_shift1,ema26_max,ema26_min,prev_max_ema26,prev_min_ema26,prev_max_ema26_date_change,prev_min_ema26_date_change,max_change_ema26,min_change_ema26,prev_max_grad_ema26,prev_min_grad_ema26,prev_grad_conv_ema26,max_move_cum_ema26,min_move_cum_ema26,long_prev_max_move_date_ema26,long_prev_min_move_date_ema26,long_max_grad_ema26,long_min_grad_ema26,long_grad_conv_ema26,change_signal_line_shift1,signal_line_max,signal_line_min,prev_max_signal_line,prev_min_signal_line,prev_max_signal_line_date_change,prev_min_signal_line_date_change,max_change_signal_line,min_change_signal_line,prev_max_grad_signal_line,prev_min_grad_signal_line,prev_grad_conv_signal_line,max_move_cum_signal_line,min_move_cum_signal_line,long_prev_max_move_date_signal_line,long_prev_min_move_date_signal_line,long_max_grad_signal_line,long_min_grad_signal_line,long_grad_conv_signal_line,change_macd_line_shift1,macd_line_max,macd_line_min,prev_max_macd_line,prev_min_macd_line,prev_max_macd_line_date_change,prev_min_macd_line_date_change,max_change_macd_line,min_change_macd_line,prev_max_grad_macd_line,prev_min_grad_macd_line,prev_grad_conv_macd_line,max_move_cum_macd_line,min_move_cum_macd_line,long_prev_max_move_date_macd_line,long_prev_min_move_date_macd_line,long_max_grad_macd_line,long_min_grad_macd_line,long_grad_conv_macd_line,change_volume_shift1,volume_max,volume_min,prev_max_volume,prev_min_volume,prev_max_volume_date_change,prev_min_volume_date_change,max_change_volume,min_change_volume,prev_max_grad_volume,prev_min_grad_volume,prev_grad_conv_volume,max_move_cum_volume,min_move_cum_volume,long_prev_max_move_date_volume,long_prev_min_move_date_volume,long_max_grad_volume,long_min_grad_volume,long_grad_conv_volume,signal'